partiql/partiql-lang-rust

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci_build_test.yml, .github/workflows/coverage.yml
Also adds pull request template.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Adds Github Action Workflows for CI/Coverage.

pest-ion/README.md
Note that the Build/Code coverage points to the workspace itself.
=> Adds badges for `pest-ion` crate README

partiql-ast/src/experimental/ast.rs, partiql-ast/tests/test_ast.rs
*Issue #, if available:* 52
* Adding more Literals based on [PartiQL Specification](https://partiql.org/assets/PartiQL-Specification.pdf).
* MISSING, NULL, COLLECTION, BOOL
* Rename `NumericLit` appending `Lit` to their names.
* Make the value of `CharStringLit` public.
* Add more documentation to `Lit`
=> Experimental ast add

partiql-parser/Cargo.toml, partiql-parser/benches/bench_parse.rs, partiql-parser/src/lalr/lexer.rs, partiql-parser/src/lalr/mod.rs, partiql-parser/src/lib.rs, partiql-parser/src/result.rs
#58 
Instrument the lexers to count lines in the lexed source.
=> Instrument the lexers to count lines in the lexed source.

partiql-ast/src/experimental/ast.rs, partiql-parser/src/lalr/lexer.rs, partiql-parser/src/lalr/mod.rs, partiql-parser/src/lalr/partiql.lalrpop, partiql-parser/src/location.rs, partiql-parser/src/result.rs
Work towards #77 
Fixes #18 
Maybe all or part of #14 
Refactor Error handling to allow multiple errors and report location
=> Refactor Error handling to allow multiple errors and report location

partiql-ast/src/ast.rs, partiql-parser/src/parse/partiql.lalrpop
Fixes #95 
Add location to SFW clauses
=> Add location to SFW clauses

partiql-ast/src/ast.rs, partiql-ast/tests/test_ast.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
#108 
Add Union/Intersect/Except to parser
Makes the the following pass: 
- https://github.com/partiql/partiql-tests/blob/main/partiql-test-data/pass/parser/primitives/union-except-intersect.ion
=> Add Union/Intersect/Except to parser

partiql-ast/src/ast.rs, partiql-parser/src/lexer.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
=> Add VALUES clause

partiql-parser/src/parse/partiql.lalrpop
*Issue #, if available:* #131 #108 
This PR includes the required changes to ensure the current
UNPIVOT conformance tests pass.
=> Make UNPIVOT conformance tests pass

partiql-conformance-test-generator/src/generator.rs, partiql-parser/src/error.rs, partiql-parser/src/lexer.rs, partiql-parser/src/lib.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop, partiql-parser/src/preprocessor.rs, partiql-source-map/src/line_offset_tracker.rs
Encapsulate parser and parse state.
=> Encapsulate parser and parse state.

partiql-conformance-tests/src/bin/generate_comparison_report.rs, partiql-conformance-tests/src/bin/generate_cts_report.rs
=> Add ignored test column to conformance test report

Cargo.toml, partiql-parser/build.rs
Also fixes a minor typo in the parser build script.
=> build: compiles build scripts with optimization

CHANGELOG.md, partiql-ast/Cargo.toml, partiql-ast/src/ast.rs, partiql-ast/src/lib.rs, partiql-ast/tests/test_ast.rs, partiql-parser/Cargo.toml, partiql-parser/src/lib.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/parser_state.rs, partiql-parser/src/parse/partiql.lalrpop, partiql-source-map/Cargo.toml, partiql-source-map/src/lib.rs, partiql-source-map/src/line_offset_tracker.rs, partiql-source-map/src/metadata.rs
- Move the source offset location that gave rise to each AST node into a `LocationMap`
- Add a unique `NodeId` to each AST node
---
=> Give AST nodes identity & decouple source location from AST node.

CHANGELOG.md, partiql-ast/src/ast.rs, partiql-ast/tests/test_ast.rs, partiql-cli/Cargo.toml, partiql-cli/src/visualize/ast_to_dot.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/parse_util.rs, partiql-parser/src/parse/partiql.lalrpop
=> Remove AST redundancies and extraneous nesting.

Cargo.toml, partiql-eval/benches/bench_eval.rs, partiql-eval/src/env.rs, partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/Cargo.toml, partiql-logical/LICENSE, partiql-logical/src/lib.rs, partiql-types/Cargo.toml, partiql-value/Cargo.toml, partiql-value/LICENSE, partiql-value/src/lib.rs
PoC basic (though anemic) value type, logical plan (needs to evolve to a graph model), and sketch of an interpreting evaluator (FROM, FROM_AT, UNPIVOT, WHERE, and SELECT)
=> PoC interpreting evaluator

partiql-value/src/lib.rs
- Fix `partiql_list` and `partiql_bag` macro_rules for repetitive values
- Minor changes to code placement in `lib.rs`
=> Some minor changes for partiql-value

partiql-eval/src/eval.rs, partiql-value/src/lib.rs
`Value` arithmatic by reference rather than taking value ownership
---
=> `Value` arithmatic by reference rather than taking value ownership

partiql-value/src/lib.rs
*Issue #, if available:* None
*Description of changes:* Previous `Debug` output was slightly confusing for `Bag` and `Tuple` values. Adjusted to be more consistent with other types and `partiql-lang-kotlin`/spec.
Previously:
```
Empty list (unchanged): []
List with elems (unchanged): [10, 10]
Empty bag: <<[]>>
Bag with elems: <<[10, 10]>>
Empty tuple: Tuple
Tuple with elems: Tuple { a: 1, b: 2 }
More complicated example: <<[Tuple { productId: 101, name: 'Mary', custId: 7, id: 7 }, Tuple { productId: 523, name: 'Mary', custId: 7, id: 7 }]>>
```
Now:
```
Empty list (unchanged): []
List with elems (unchanged): [10, 10]
Empty bag: <<>>
Bag with elems: <<10, 10>>
Empty tuple: {}
Tuple with elems: { a: 1, b: 2 }
More complicated example: <<{ id: 7, name: 'Mary', productId: 101, custId: 7 }, { …
```
=> Adjust `Debug` formatting for `Bag` and `Tuple` values

partiql-value/src/lib.rs
*Issue #, if available:* None.
*Description of changes:* Addresses a [TODO from a previous PR](https://github.com/partiql/partiql-lang-rust/pull/210#discussion_r1014528728) related to `eq` and `neq` between numeric types. Implements equality between different numeric types (e.g. `1` = `1.0` => `true`). Previously, equality between different numeric types would always return `false`.
Also adds some more tests related to container equality from the PartiQL spec [section 7.1.1](https://partiql.org/assets/PartiQL-Specification.pdf#subsubsection.7.1.1).
=> Implement Value `eq` and `neq` between numeric types

partiql-value/Cargo.toml, partiql-value/src/ion.rs, partiql-value/src/lib.rs
Add partial parsing of ion into Value
=> Add partial parsing of ion into Value

partiql-eval/src/env.rs
Additional `From` impls for MapBindings
=> Additional `From` impls for MapBindings

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs
=> Minor cleanup/reformatting/clippy suggestions

partiql-value/src/ion.rs
Fix ion symbol parsing to property extract the symbol text.
previously it would transform something like `` `'a'` `` into a partiql value of `'\'a\''`, when it should be `'a'`
---
=> Fix ion symbol parsing to property extract the symbol text.

partiql-eval/src/eval.rs
Do proper null-propagation for concat
---
=> Do proper null-propagation for concat

partiql-logical-planner/src/lower.rs
Lower `BETWEEN` expressions from AST to logical plan
---
=> Lower `BETWEEN` expressions from AST to logical plan

partiql-eval/Cargo.toml, partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/pattern_match.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql-parser/Cargo.toml
Implement LIKE pattern match lowering and evaluation
Pattern compilation taken from https://github.com/partiql/partiql-lang-rust/pull/98
---
=> Implement LIKE pattern match lowering and evaluation

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs
Support optional AT for UNPIVOT
---
=> Support optional `AT` for `UNPIVOT`

partiql-conformance-tests/tests/mod.rs, partiql-conformance-tests/tests/test_value.rs, partiql-logical-planner/src/lower.rs, partiql-parser/src/preprocessor.rs
Clean up clippy warnings and some minor renames
---
=> Clean up clippy warnings and some minor renames

partiql-logical-planner/src/lower.rs
Add lowering of Simple & Searched `CASE` expressions
---
=> Add lowering of Simple & Searched `CASE` expressions

partiql-parser/src/parse/partiql.lalrpop
cleanup up some clippy recommendations in the lalrpop parser
---
=> cleanup up some clippy recommendations in the lalrpop parser

CHANGELOG.md, Cargo.toml, README.md, partiql-ast/Cargo.toml, partiql-conformance-test-generator/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-logical-planner/Cargo.toml, partiql-logical/Cargo.toml, partiql-parser/Cargo.toml, partiql-parser/fuzz/Cargo.toml
Releases v0.2.0. Also makes edits to the CHANGELOG and README.
=> Release v0.2.0

CHANGELOG.md
Some links were outdated/missing from previous releases. Updated in this PR
=> Update CHANGELOG links

.github/workflows/benchmark.yml, Cargo.toml
Uses https://github.com/benchmark-action/github-action-benchmark
Cf. [The action's rust example](https://github.com/benchmark-action/github-action-benchmark/tree/master/examples/rust)
Cf. [A similar PR for partiql-lang-kotlin](https://github.com/partiql/partiql-lang-kotlin/pull/921)
---
=> Adds performance benchmarking to GitHub actions

partiql-eval/src/eval.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/call_defs.rs, partiql-logical/src/lib.rs, partiql-parser/src/preprocessor.rs
- Add implementations for position, ocetet_len, bit_len
- Update partiql-tests
---
=> Add built-in functions: position, ocetet_len, bit_len

partiql-eval/src/eval.rs
Refactors `EvalExpr`'s `evaluate` function to return a [`Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html#).
Expressions like paths and variable reference return a `Cow::Borrowed` value and value-generating expressions (e.g., `+`, `trim`, ||`, etc) return a `Cow::Owned` value.
Locally, this results in a ~15% to ~30% speedup on evaluation benchmarks and ~40% speedup of the run of the entire conformance test suite.
Running `cargo bench eval`
before:
```
12:52❯ RUST_BACKTRACE=1 cargo bench eval
Finished bench [optimized + debuginfo] target(s) in 0.56s
Running benches/bench_eval_multi_like.rs (target/release/deps/bench_eval_multi_like-46418ead6aae5482)
eval-1                  time:   [24.835 ms 25.307 ms 25.896 ms]
change: [-10.626% -8.1034% -4.7672%] (p = 0.00 < 0.05)
Performance has …
```
=> Change EvalExpr.evalute to return `Cow`s to avoid unnecessary clones

partiql-value/src/lib.rs
- Add `Extend` implementations for `List` and `Bag`
- Add methods to iterate a `Tuple`'s values without zipping its names
- Allow `collect()` into a `Tuple` with any `Into<String>`
- other minor cleanup
---
=> Add some convenience methods and cleanup of `Value`

partiql-eval/src/eval.rs
=> Cache `Evaluable`'s "attrs" at construct time, and return by ref

partiql-eval/src/eval.rs
=> Cleanup evaluator to more idiomatically use `.collect()` throughout

partiql-parser/src/parse/parser_state.rs
Should fix the parsing performance benchmark regression.
Cf. http://partiql.org/partiql-lang-rust/dev/bench/
Cf. https://github.com/partiql/partiql-lang-rust/commit/320c6297315465f6a97297b6d356a55bbadc4894#commitcomment-100912787
---
=> Build Aggregate function recognizer only once, using OnceCell

partiql-parser/src/preprocessor.rs
=> Pass-through comments when preprocessing special forms

partiql-ast/src/ast.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
Cf. https://github.com/partiql/partiql-tests/blob/b8ddd15440dc0e5831a05e567b905c6736d045a2/partiql-tests-data/eval/primitives/operators/bag-operators.ion
---
=> Parse `OUTER` `UNION`/`INTERSECT`/`EXCEPT`

partiql-eval/src/eval/expr/mod.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/call_defs.rs, partiql-logical/src/lib.rs, partiql-parser/src/preprocessor.rs
=> Add `ABS`, `MOD`, `CARDINALITY`, and `OVERLAY` built-ins

.gitmodules
=> Update to latest `partiql-tests`

partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
=> Clean up some clippy warnings

partiql-conformance-test-generator/src/util.rs
Will be needed for https://github.com/partiql/partiql-tests/pull/68
---
=> Handle test/mod names that start with a digit

partiql-parser/src/lexer.rs, partiql-parser/src/parse/mod.rs
Adds a comment-skipping lexer wrapper to discard comment tokens prior to parsing.
---
=> Properly skip comments when parsing

CHANGELOG.md
Updates CHANGELOG ahead of v0.3.0 release.
---
=> Update CHANGELOG ahead of 0.3.0 release

partiql-conformance-test-generator/Cargo.toml, partiql-conformance-test-generator/src/reader.rs, partiql-conformance-tests/Cargo.toml, partiql-conformance-tests/tests/test_value.rs, partiql-value/Cargo.toml, partiql-value/src/ion.rs
=> Upgrade ion-rs from 0.16 to 0.17

partiql-value/src/bag.rs, partiql-value/src/list.rs, partiql-value/src/tuple.rs
=> Fix bag,list,tuple mcaros to fully qualify type `Bag`,`List`,`Tuple`

partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/mod.rs, partiql-logical-planner/src/lower.rs
=> Add plan flows for JOIN. Add 'self managed' graph nodes. 

CHANGELOG.md, Cargo.toml, extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion/Cargo.toml, partiql-ast/Cargo.toml, partiql-catalog/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-logical-planner/Cargo.toml, partiql-logical/Cargo.toml, partiql-parser/Cargo.toml
=> v0.5.0 Release prep.

extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion/Cargo.toml, extension/partiql-extension-ion/src/lib.rs, partiql-conformance-test-generator/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-logical-planner/Cargo.toml, partiql-value/Cargo.toml
=> Upgrade ion-rs to 0.18

CHANGELOG.md, extension/partiql-extension-ion-functions/src/lib.rs, partiql-conformance-tests/tests/mod.rs, partiql-eval/benches/bench_eval.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lib.rs, partiql/benches/bench_eval_multi_like.rs
No implementation currently, just the interface.
---
=> Add interface for strict mode evaluation.

partiql-conformance-tests/tests/mod.rs
=> Fix `fail_semantics` function

partiql/Cargo.toml, partiql/benches/bench_agg.rs
=> Add benchmarks for aggregation functions, group by, group as

CHANGELOG.md, Cargo.toml, extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion/Cargo.toml, extension/partiql-extension-visualize/Cargo.toml, partiql-ast-passes/Cargo.toml, partiql-ast/Cargo.toml, partiql-catalog/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-logical-planner/Cargo.toml, partiql-logical/Cargo.toml, partiql-parser/Cargo.toml, partiql-source-map/Cargo.toml
Release for v0.7.0 
Command run:
```
cargo release minor --no-publish --no-push -x
```
---
=> chore: Release v0.7.0

CHANGELOG.md, Cargo.toml
=> chore: Release v0.7.1

CHANGELOG.md, Cargo.toml, extension/partiql-extension-ddl/Cargo.toml, extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion/Cargo.toml, extension/partiql-extension-visualize/Cargo.toml, partiql-ast-passes/Cargo.toml, partiql-ast/Cargo.toml, partiql-catalog/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-logical-planner/Cargo.toml, partiql-logical/Cargo.toml, partiql-parser/Cargo.toml, partiql-source-map/Cargo.toml
=> chore: Release v0.8.0

CHANGELOG.md, extension/partiql-extension-ddl/src/ddl.rs, partiql-logical-planner/src/typer.rs, partiql-types/src/lib.rs
=> Refactors to make working with types a bit more ergonomic

CHANGELOG.md, Cargo.toml, extension/partiql-extension-ddl/Cargo.toml, extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion/Cargo.toml, extension/partiql-extension-visualize/Cargo.toml, partiql-ast-passes/Cargo.toml, partiql-ast/Cargo.toml, partiql-catalog/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-logical-planner/Cargo.toml, partiql-logical/Cargo.toml, partiql-parser/Cargo.toml, partiql-source-map/Cargo.toml
Release for v0.10.0 
Command run:
```
cargo release minor --no-publish --no-push -x
```
---
=> chore: Release v0.10.0

deny.toml, extension/partiql-extension-value-functions/Cargo.toml
=> Update some dependencies and deny checks

CHANGELOG.md, Cargo.toml, extension/partiql-extension-ddl/Cargo.toml, extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion/Cargo.toml, extension/partiql-extension-value-functions/Cargo.toml, extension/partiql-extension-visualize/Cargo.toml, partiql-ast-passes/Cargo.toml, partiql-ast/Cargo.toml, partiql-catalog/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-logical-planner/Cargo.toml, partiql-logical/Cargo.toml, partiql-parser/Cargo.toml, partiql-types/Cargo.toml
Release for v0.11.0 
Command run:
```
cargo release minor --no-publish --no-push -x
```
---
=> chore: Release v0.11.0

extension/partiql-extension-ddl/Cargo.toml, extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion/Cargo.toml, extension/partiql-extension-value-functions/Cargo.toml, partiql-ast-passes/Cargo.toml, partiql-conformance-test-generator/Cargo.toml, partiql-parser/Cargo.toml, partiql-types/Cargo.toml, partiql-value/Cargo.toml
=> Remove some unused dependencies

CHANGELOG.md, partiql-parser/src/error.rs, partiql-parser/src/parse/mod.rs
=> Add a source location for UnexpectedEndOfInput parse error

.github/workflows/ci_build_test.yml
- #520 
- `actions/upload-artifact@v3` -> `actions/upload-artifact@v4`
- `dawidd6/action-download-artifact@v2` -> `actions/download-artifact@v4`
=> Bump upload and download artifact versions

extension/partiql-extension-ion/src/decode.rs
=> Fix warnings/errors newly surfaced by rust/clippy 1.84

extension/partiql-extension-ddl/src/ddl.rs
Fixing what seems to have been a typo introduced by #485 
---
=> Fix DDL output for `Array` and `Bag` types.

partiql-ast/src/pretty.rs, partiql-value/src/pretty.rs
=> Fix pretty-print implementation to not use transmute.

CHANGELOG.md
=> Update Changelog unreleased

CHANGELOG.md, Cargo.toml, extension/partiql-extension-csv/Cargo.toml, extension/partiql-extension-csv/resources/test/people.csv, extension/partiql-extension-csv/resources/test/pets.csv, extension/partiql-extension-csv/src/lib.rs, extension/partiql-extension-csv/tests/scan.rs, extension/partiql-extension-csv/tests/snapshots/scan__join.snap, extension/partiql-extension-csv/tests/snapshots/scan__people.csv.errors.snap, extension/partiql-extension-csv/tests/snapshots/scan__people.csv.snap, extension/partiql-extension-csv/tests/snapshots/scan__pets.csv.errors.snap, extension/partiql-extension-csv/tests/snapshots/scan__pets.csv.snap
Adds a very simple CSV reading extension.
---
=> Add partiql-extension-csv

partiql-value/src/bindings.rs, partiql-value/src/value.rs
Use features from #533 for tuple coercion.
---
=> Use `Datum` for tuple coercion/bindings

partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql/tests/queries.rs
=> Handle subqueries in the FROM clause

CHANGELOG.md, extension/partiql-extension-csv/tests/scan.rs, partiql-logical-planner/src/lower.rs
=> Fix interactions between GROUP BY and subqueries

.github/workflows/ci_build_test.yml, .github/workflows/coverage.yml
similar PR for PLK https://github.com/partiql/partiql-lang-kotlin/pull/1750
prior ubuntu-20.04 runner was deprecated and removed. updating to the latest in this PR
=> ci: update GH Actions ubuntu runner

partiql/Cargo.toml, partiql/benches/bench_join.rs
=> Add join benchmarks

CHANGELOG.md, partiql-eval/src/eval/graph/plan.rs, partiql-eval/src/eval/graph/simple_graph/engine.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/graph.rs, partiql-logical/src/graph/mod.rs
Lower & evaluate graph match label negation,conjunction disjunction
---
=> Lower & evaluate graph match label negation,conjunction disjunction

partiql-parser/src/lib.rs
=> Add some documentation for printing error messages nicely

CHANGELOG.md, Cargo.toml, extension/partiql-extension-csv/Cargo.toml, extension/partiql-extension-ddl/Cargo.toml, extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion/Cargo.toml, extension/partiql-extension-value-functions/Cargo.toml, extension/partiql-extension-visualize/Cargo.toml, partiql-ast-passes/Cargo.toml, partiql-ast/Cargo.toml, partiql-catalog/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-logical-planner/Cargo.toml, partiql-logical/Cargo.toml, partiql-parser/Cargo.toml, partiql-types/Cargo.toml, partiql-value/Cargo.toml
=> chore: Release v0.14.0
