partiql/partiql-lang-rust

README.md
Note that I only put the crate/docs badge for the `partiql` crate
as we'll likely re-export dependencies there anyhow for a one stop
shop for PartiQL APIs.  We can always put them all here if we like.
=> Adds Badges to README.

.github/codecov.yml
`grcov` can be pretty noisy in coverage, so the auto targets for this
can lead to a lot of check failures that seem pedantic.
Tested with:
`curl --data-binary @.github/codecov.yml https://codecov.io/validate`
=> Adds a fixed codecov.yml target.

.github/codecov.yml, .github/workflows/coverage.yml
The Pest generated parser yields code paths that are hard to target for
coverage.  This is not an excuse to not target good coverage, but we
should do this systematically through broader PartiQL tests and/or fuzz
testing.
This also updates the coverage CI to `nightly-2021-05-09`.
=> Adds ignore for peg.rs and updates nightly for coverage

partiql-parser/src/lib.rs, partiql-parser/src/partiql.pest, partiql-parser/src/peg.rs, partiql-parser/src/prelude.rs, partiql-parser/src/result.rs, partiql-parser/src/scanner.rs
Provides an interface for _lexing_ PartiQL.  Traditionally we would
factor this as the low-level interface for the parser, but with the PEG
based implementation, we just surface the relevant parts of the parser
as a rule to parse with.
This commit helps explore how to effectively integrate with the somewhat
low-level APIs for parsing that Pest provides.
Notes:
* Adds `scanner` module.
* Adds `Scanner` trait to the prelude.
* Makes `PartiQLParser` public to crate.
* Refactors `LineAndColumn` as a tuple for `Position::At`.
- Adds this to the `prelude`.
* Changes entry point for PEG to `Query` and added `Scanner` as the
entry point rules for implementing the `Scanner` API.
* Adds `PairsExt`/`PairExt` trait/impl to add utility methods for working
with Pest `Pairs`/`Pair`.
* Adds …
=> Initial API for `Scanner`.

partiql-parser/src/peg.rs, partiql-parser/src/result.rs
*Issue #, if available:* #23
*Description of changes:* Adds a unit variant `IllegalState` to ParserError enum. [Users](https://github.com/partiql/partiql-lang-rust/pull/12#discussion_r635494493) of the enum would call `illegal_state()` convenience function.
=> First issue

partiql-parser/src/lib.rs, partiql-parser/src/partiql.pest, partiql-parser/src/peg.rs, partiql-parser/src/scanner.rs
Refactors the PEG to make each keyword and explicit rule that has the
form `KeywordName_`.  This allows us to easily refer to them in rules
without having to have magic strings.  The rationale for the `_` suffix
is to make sure it doesn't collide with the other grammar rules and not
have a wordy suffix like `Keyword` on every rule.
Also:
* Adds case folding to keywords.
* Makes error cases in the scanner/recognizer tests less brittle.
* Adds `Token` to the `Query` rule and updates tests for
`recognize_partiql`.
Depends on #8 and #12--as such is targeting a staging branch but I did not want to prevent review.
Rendered update of the doc test that exercises some of this:
=> Adds support for string literals and identifiers in `Scanner`.

partiql-parser/Cargo.toml, partiql-parser/src/lib.rs, partiql-parser/src/partiql.pest, partiql-parser/src/peg.rs, partiql-parser/src/scanner.rs
Specifically adds the `Number` rule for parsing decimals and integers.
Also adds the `IntegerLiteral` and `DecimalLiteral` to capture the
respective literal tokens.
Notes:
* Adds `num-traits`, `num-bigint`, and `bigdecimal` to provide support
for integer/decimal parsing.
* Adds `PairExt::unexpected()` for dealing with unexpected rules.
* Adds `PairExt::syntax_error()` for easily creating syntax errors from a pair.
* Updates scanner doc test to `panic!` for unexpected tokens.
* Fixes the bad recognizer test because it only has scanner support and we
cannot detect that `99_RANCH` is syntactically incorrect but lexes to
`99` and `_RANCH`.  Real PartiQL parsing will fix this in the future.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Adds numeric literals to grammar.

partiql-parser/src/result.rs, partiql-parser/src/scanner.rs
Previously, the `Scanner` tests required a lot of manual position
expectations which was tedious to write.  This replaces that with a test
harness that can do the math from chunks of input that the test writer
defines as whitespace or token boundaries.  This also adds the macro
`scanner_test_case!` which makes it so that one can use the harness with
a friendly syntax. The old tests are ported to the new macro.
Also:
* Adds assertions to the internal `LineAndColumn::at`.
* Adds convenience constructor around `Content`.
Resolves #21.
=> Streamlines the `Scanner` Tests.

partiql-parser/src/partiql.pest, partiql-parser/src/result.rs, partiql-parser/src/scanner.rs
*Issue:* 
#17 
*Description of changes:* 
I added COMMENT rule to the pest grammar. I was hesitant to edit the Rule::Query as well. Should I?
=> Add COMMENT to Scanner grammar rule

partiql-parser/src/partiql.pest, partiql-parser/src/scanner.rs
This applies some very minor changes that I meant to apply as part
of #25, but forgot to before merging.
Also removes some redundant `#[rstest]` attributes in the tests
and makes the spacing in the PEG more consistent around parenthesis.
=> Applies minor style fixes.

partiql-parser/src/partiql.pest, partiql-parser/src/scanner.rs
Adds the Pest grammar rules for these tokens and particularly
adds the lookahead assertions for the various edge cases around the
punctuation tokens that interact with each other and comments.
Adds special `Content` enum variants for `.`/`*`/`?` and a basic variant
for `Operator` and `Delimiter`.
This should the final pre-requisite for all of the terminal parse rules in
the PEG and allow us to start adding the parser rules for expressions.
An explicit TODO is around modeling the various operators as their own
enum or enum variants, right now they are returned as normalized string
content.
=> Adds the scanner rules for punctuation

partiql-parser/src/partiql.pest, partiql-parser/src/scanner.rs
Previously, `SELECTY` would be parsed as keyword `SELECT` identifier
`Y`.  This fixes the negative look-ahead assertion for keywords to
make sure a non-quoted identifier character follows and similarly
adds a look-ahead assertion for the prefix of identifiers to not be
keywords (which includes the previous assertion).
Also fixes a unit test name.
=> Fixes an ambiguity with identifiers and keywords.

partiql-parser/src/partiql.pest, partiql-parser/src/peg.rs
The grammar breaks out `SelectExpression` from `ValueExpression` but
unifies them with grouping.  This is actually not supported in the
Kotlin parser, but is actually the correct form in my opinion.
Also cleans up atomicity/silencing in the dependent terminal rules and
while doing this, the spacing was adjusted to make this easier to read.
More specifically, all punctuation is basically silent because grammar rules
don't want them to be in the parse, and keywords are also silent because
the grammar enforces the structure.  Operators on the other hand are
atomic and visible because they are used in the parse tree to drive
precedence climbing/Pratt processing and are thus required to be
visible.
This is clearly not a complete grammar, nor are the tests sufficient,
but this is a good …
=> Fills in the start of a real PartiQL grammar.

pest-ion/src/result.rs
Fixes broken link to `std::error::Error`, qualifies it because of the
ambiguity to the derive macro.
=> Minor fix to doc comment in `pest_ion::result`

pest-ion/Cargo.toml, pest-ion/src/lib.rs, pest-ion/src/result.rs
Removes `smallvec` and changes expression serialization to use heap
allocated `Vec`.  For very heavily nested grammars (e.g. PartiQL's
keyword rules), this can blow out the stack.
Adds support for `TryPestToElement` from `Read` via a wrapper.
Interior mutability via `RefCell<T>` is required because `TryPestToElement`
is designed around `&self` which makes sense for things like `&str`/`String`/`Path`.
Also:
* Adds blanket `TryPestToElement` implementation for all references.
* Adds `TryPestToElement` implementations for `Path` and `String`.
* Adds test to load PartiQL Pest.
* Adds `PestToIonError::Io`.
=> Load file implementation of `TryPestToIon`

pest-ion/Cargo.toml, pest-ion/src/bin/pest2ion/main.rs
Adds a basic CLI driver over the `pest-ion` crate.  This driver supports
setting the input file (defaulting to STDIN), an output file (defaulting
to STDOUT), and flags around the Ion data format.
An explicit TODO is to figure out a good way to test this probably using
integration tests and spawning the command. (See #42)
Resolves #36.
=> Adds `pest2ion` command

pest-ion/Cargo.toml, pest-ion/tests/cli.rs
Uses `assert_cmd` and `rstest` to test the different permutations of the
`pest2ion` command with real arguments.  This includes testing
STDIN/STDOUT defaults as well as file arguments using a temporary
directory per test case.  Each format mode is also permuted.
Note that this does not test the "long" argument names, if we care to,
we can always add that for completeness.
The goal here is to make sure the driver works, not to test the completeness
of the `pest-ion` library crate.
Resolves #42.
=> Adds CLI tests for `pest2ion`

pest-ion/src/lib.rs
Implements a `flatten` a higher-order function to operate on binary
operators that have associativity like `choice`/`sequence`.
Resolves #37.
=> Flattens `choice`/`sequence` operators

pest-ion/tests/cli.rs
Adds a `TestCase` struct to encapsulate the test case parameters for
testing the CLI.  Makes a simple conversion from `&'static str` pair
which is for when you have simple in/out type of tests.  Adds function
to generate a test case out of the PartiQL grammar file which doesn't
really validate anything about the grammar serialization other than we
get something the library would produce.
=> Adds `pest2ion` CLI test for PartiQL Grammar

.github/workflows/coverage.yml
We're getting some odd errors in GitHub action when building
our dependencies, upgrading the toolchain to resolve such errors.
```
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ion-c-sys-macros-0.1.1/Cargo.toml`
Error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ion-c-sys-macros-0.1.1/Cargo.toml`
Caused by:
feature `edition2021` is required
consider adding `cargo-features = ["edition2021"]` to the manifest
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```
=> Upgrade toolchain for GitHub coverage.yaml

.github/codecov.yml, Cargo.toml, partiql-ast/Cargo.toml, partiql-ast/LICENSE, partiql-ast/src/experimental/ast.rs, partiql-ast/src/lib.rs, partiql-ast/tests/common.rs, partiql-ast/tests/test_ast.rs
*Issue #, if available:* 52
This commit includes an experimental implementation of PartiQL AST
based on the current kotlin implementation which has been
auto-generated by `partiql-ir-generator`:
- https://github.com/partiql/partiql-ir-generator
We want to create an experimental PartiQL AST so that:
- solidify our expected core model (at least for the first iteration)
prior to developing AST code generation i.e. using
partiql-ir-generator spec or a substitute.
- we can get an early review with having integration with parser
in the picture.
This implementation does _not_ include:
- The addition of MetaContainer and with_meta method.
For code region data, We try to see if a substitute approach like
using Span works as a substitute approach.
- The implementation of …
=> Add Experimental AST

partiql-parser/Cargo.toml, partiql-parser/benches/bench_parse.rs, partiql-parser/src/lib.rs, partiql-parser/src/peg/ast_builder.rs, partiql-parser/src/peg/grammar.rs, partiql-parser/src/peg/mod.rs, partiql-parser/src/peg/partiql.pest
#58 
This prototypes AST creation from the PEG grammar. 
The code is not particularly well documented, nor is it comprehensive of the grammar/AST. Rather this is basically the minimal amount of AST building necessary to pass the existing set of parser tests. 
The intent is to be able to assess the general readability/complexity of parsing from text to AST in order to compare the LALRPOP vs PEG approaches.
=> Add prototype for converting Pest's Pairs to AST

partiql-parser/benches/bench_parse.rs, partiql-parser/src/lalr/lexer.rs
#58
* Add embeddable block comment lexer
* Add embeddable ion lexer, including block comment lexer
* Refactor PartiQL lexer to embed the ion & block comment lexers
* Add ion lexing & bench tests
* Add lexer error tests
=> Rework embedded ion & comment lexers.

partiql-ast/src/experimental/ast.rs, partiql-ast/tests/test_ast.rs, partiql-parser/src/lalr/partiql.lalrpop, partiql-parser/src/peg/ast_builder.rs
*Issue #, if available:* 62
PR Issue: https://github.com/partiql/partiql-lang-rust/issues/63
Considered two approaches:
1. Apply the changes as recommended by clippy
2. Box Exprs to reduce the overall size.
This PR applies the second approach.
Benchmark results:
$ cargo bench
...
Gnuplot not found, using plotters backend
peg-simple              time:   [2.2424 us 2.2828 us 2.3286 us]
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
peg-ion                 time:   [12.924 us 13.084 us 13.269 us]
Found 11 outliers among 100 measurements (11.00%)
9 (9.00%) high mild
2 (2.00%) high severe
peg-group               time:   [29.023 us 29.692 us 30.459 us]
Found 12 outliers among 100 measurements (12.00%)
4 (4.00%) high mild
8 (8.00%) high severe …
=> Remove ast clippy warnings

partiql-parser/src/lalr/mod.rs, partiql-parser/src/lalr/partiql.lalrpop
#58
`AT` is only allowed in an `UNPIVOT`  From clause.
=> Model UNPIVOT correctly in grammar.

partiql-ast/src/experimental/ast.rs
*Issue #, if available:* #60
This change adds a Display formatting to the `Item` and re-uses Debug
formatting for now.
Example:
```bash
Query(Query { expr: Expr { kind: Lit(Lit { kind: NumericLit(NumericLit { kind: Int32Lit(Int32Lit { value: 12 }) }) }) } })
```
=> Add Display formatting to Item

partiql-eval/Cargo.toml, partiql-irgen/Cargo.toml, partiql-parser/Cargo.toml, partiql-rewriter/Cargo.toml, partiql/Cargo.toml, pest-ion/Cargo.toml
Fixes #69 
Updates all crates to `edition = "2021"`
=> Update all crates to edition = "2021"

.github/workflows/ci_build_test.yml, partiql-parser/src/peg/ast_builder.rs
*Issue #, if available:* 66
- Adds Clippy GitHub Actions step
- Resolves irrefutable _if let_ pattern clippy warnings
We have the following remaining warnings. For _lex_partiql_ we'll resolve the warning once we're final with our _lexer_ impl. when finalizing M1.
```bash
warning: use of deprecated function `lalr::lex_partiql`: prototypical lexer implementation
--> partiql-parser/src/lib.rs:17:15
|
17 | pub use lalr::lex_partiql as logos_lex;
|               ^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: use of deprecated function `lalr::lex_partiql`: prototypical lexer implementation
--> partiql-parser/src/lalr/mod.rs:35:17
|
35 |     let lexer = lex_partiql(s);
|                 ^^^^^^^^^^^
warning: associated function is never used: `at`
--> …
```
=> Add clippy

partiql-parser/src/lalr/lexer.rs, partiql-parser/src/lalr/mod.rs, partiql-parser/src/lalr/partiql.lalrpop, partiql-parser/src/peg/mod.rs, partiql-parser/src/result.rs
#77 
Refactors lexer to use `&str` references instead of `String`s as token data as per http://lalrpop.github.io/lalrpop/lexer_tutorial/003_token_references.html
=> Refactor lexer to use &str slices rather than Strings in tokens

partiql-ast/Cargo.toml, partiql-ast/src/experimental/ast.rs, partiql-ast/src/lib.rs, partiql-parser/Cargo.toml, partiql-parser/benches/bench_parse.rs, partiql-parser/build.rs, partiql-parser/src/lexer.rs, partiql-parser/src/lib.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop, partiql-parser/src/result.rs, partiql-source-map/src/lib.rs, partiql-source-map/src/line_offset_tracker.rs, partiql-source-map/src/location.rs
Fixes #77
- Add documentation 
- Export types that should be public
- Rename some Error/Result types for better consistency
=> Cleanup the Parser API and add some documentation

partiql-ast/src/ast.rs, partiql-ast/src/lib.rs, partiql-ast/tests/test_ast.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop, partiql-parser/src/result.rs
*Issue #, if available:* #81
This change moves the AST out of experimental module. Based on the recent
changes made, while we still consider future changes to the AST we've agreed
to move the AST out of experimental module as a requirement for M1 milestone.
=> Move AST out of experimental

partiql-ast/src/ast.rs, partiql-ast/tests/test_ast.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
First work towards #95 
Adds location sensing to some `Expr` nodes to store the `BytePosition` of the source text in the Ast.
=> Refactor some `Expr`s to add location to parsed AST nodes

partiql-ast/src/ast.rs, partiql-parser/src/parse/partiql.lalrpop
*Issue #, if available:* #95
See PR #103 for more context on adding location data `AstNode`.
In this commit we make the following changes:
- Add the remaining `ExprKind` to AstNode and modify the parser
to include the location information to the corresponding AstNodes.
- Remove ExprPairList and use the Vec<Expr> directly.
- Remove redundant Date and Time structures
We already have the DateTime Literal so removing the redundant ones
in the AST.
=> Add remaining location to remaining AstNodes

.github/workflows/ci_build_test.yml, README.md, partiql-conformance-test-generator/src/lib.rs, partiql-conformance-test-generator/src/util.rs, partiql-conformance-tests/Cargo.toml, partiql-conformance-tests/README.md, partiql-conformance-tests/build.rs
Changes as part of this PR:
- Updates `partiql-tests` submodule following latest test additions in https://github.com/partiql/partiql-tests/pull/10.
- Disables running the conformance tests by default (i.e. `cargo test`) and adds a feature flag to `partiql-conformance-tests` that can be set to run the conformance tests
- More details included in the `partiql-conformance-tests` `README.md`
- Adds a GitHub actions workflow step that runs the conformance tests separately using the [continue-on-error](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) flag
- This will allow the GitHub Actions build to succeed even if a conformance test fails
- Further conformance report generation will be done as part of #79
By submitting this …
=> Update `partiql-tests` submodule; add feature to `partiql-conformance-tests` crate

partiql-conformance-test-generator/src/generator.rs
#108 
Add some details to conformance test assert output.
Old output:
```
assertion failed: partiql_result.is_ok()
```
New output:
```
For `COUNT(DISTINCT a)`, expected `Ok(_)`, but was `Err(
[
UnexpectedToken(
Located {
inner: UnexpectedTokenData {
token: "<IDENTIFIER>",
},
location: Location {
start: LineAndColumn {
line: 1,
column: 16,
},
end: LineAndColumn {
line: 1,
column: 17,
},
},
},
),
],
)`
```
=> Add details to Parse test asserts

partiql-parser/src/lexer.rs, partiql-parser/src/parse/partiql.lalrpop
#108 
Fixes parsing of `GROUP [ALL|PARTIAL] BY...`
Makes the following pass:
- https://github.com/partiql/partiql-tests/blob/main/partiql-test-data/pass/parser/query/select/group-by.ion#L16-L22
=> Fixes parser for GROUP `ALL`|`PARTIAL`

partiql-parser/src/lexer.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
#108 
Makes the following pass:
- https://github.com/partiql/partiql-tests/blob/main/partiql-test-data/pass/parser/query/pivot.ion#L9-L15
=> Add `||` (concat) infix operator

partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
#108 
Add sql-compatibility parsing of arrays in parens if at least 2 elements
See 6.1.2 of https://partiql.org/assets/PartiQL-Specification.pdf
Makes the following pass:
- https://github.com/partiql/partiql-tests/blob/main/partiql-test-data/pass/parser/primitives/container-constructors.ion#L1-L20
- https://github.com/partiql/partiql-tests/blob/main/partiql-test-data/pass/parser/primitives/operators/in-operator.ion#L1-L29
=> Add sql-compatibility parsing of arrays in parens if at least 2 elements

partiql-ast/src/ast.rs, partiql-parser/src/lexer.rs, partiql-parser/src/parse/partiql.lalrpop
*Issue #, if available:* #108 
This PR resolves the comments in [PR-109](https://github.com/partiql/partiql-lang-rust/pull/109).
The changes involve are:
- Creation of `Distinct` keyword.
- Creation of `SetQuantifierStrategy` for making statements with `SetQuantifier` parsable.
- Fixes parsing of general function calls (excluding functions like `substring` for now).
The reason for creating a new PR is that the previous PR is polluted with commits from other merges.
Conformance test report:
https://paste.debian.net/1239858/
=> Resolve parser conformance tests (initial PR)

partiql-ast/src/ast.rs, partiql-parser/src/lexer.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
*Issue #, if available:* #119, #108
Adds CASE expression parsing
GitHub Issue: #119
Adds the required constructs to enable CASE EXPRESSION parsing. The PR includes changes to `partiql-ast` and `partiql-parser` to handle`SearchedCase` and `SimpleCase` parsing.
See the mentioned GitHub issue for more details.
As a result of the changes in this PR, the conformance tests in the following pass:
https://github.com/partiql/partiql-tests/blob/main/partiql-test-data/pass/parser/primitives/case.ion
=> Parse case expr

partiql-ast/src/ast.rs, partiql-ast/tests/test_ast.rs, partiql-parser/src/lexer.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
*Issue #, if available:* #108, #121
This PR includes changes for enabling Parser to parse
Path Navigations as specified in Section 4 of PartiQL
Specification. It also ensures the following tests go through:
https://github.com/partiql/partiql-tests/blob/c76715ddb95ba6eec2d34ca500077b6e7eba9e35/partiql-test-data/pass/parser/primitives/path-expression.ion
The following PR in `partiql-tests` is created for adding additional conformance
tests for path expressions:
https://github.com/partiql/partiql-tests/pull/13
In addition:
- the PR introduces `dbl_quoted` property to `SymbolPrimitive`
in order to cater for symbol primitives that are double quoted, e.g.
`AS "date".
- Splits `Identifier` to `QuotedIdentifier` and `UnquotedIdentifer`
in order for the parser to populate …
=> Add remaining path expressions to parser

partiql-ast/src/ast.rs, partiql-parser/Cargo.toml, partiql-parser/benches/bench_parse.rs, partiql-parser/src/lexer.rs, partiql-parser/src/lib.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop, partiql-parser/src/preprocessor.rs, partiql-parser/src/token_parser.rs
#108 
Model functions in "Core" PartiQL as taking either positional or named arguments. On top of that, model SQL special "function expressions" (e.g. `position('o' in 'foobar')`, etc) as preprocessed translations into named arguments (e.g., `position('o', in: 'foobar')`.
- Add named parameter parsing for functions
- Streaming translate SQL function expressions into functions with named arguemnts
This translates calls like:
- `substring(a from 2 for 3)`
- `trim(leading 't' from 'ttthere')`
- `cast(a as VARCHAR)`
Into:
- `substring(a, "from":2, "for":3)`
- `trim("leading": 't', "from": 'ttthere')`
- `cast(a, "as":VARCHAR)`
=> Add modifiers and named parameter parsing for functions.

.github/workflows/ci_build_test.yml
GitHub actions failed for a previous build due to a mismatch between the downloaded conformance artifact directory and the expected path of the conformance artifact. Example build failure: https://github.com/partiql/partiql-lang-rust/runs/6780646755?check_suite_focus=true
This PR should fix the directory mismatch.
Still awaiting the result of the GitHub actions run to ensure the directory mismatch is resolved.
=> Fix downloaded conformance report directory

Cargo.toml, partiql-cli/Cargo.toml, partiql-cli/LICENSE, partiql-cli/README.md, partiql-cli/src/bin/ion.sublime-syntax, partiql-cli/src/bin/partiql-cli.rs, partiql-cli/src/bin/partiql.sublime-syntax, partiql-parser/benches/bench_parse.rs, partiql-parser/src/error.rs, partiql-parser/src/lib.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/preprocessor.rs, partiql-parser/src/token_parser.rs
This is a minimal PoC for the start of a REPL. It should be considered experimental, subject to change, etc.
I wrote this in order to test the parser interface & types from the perspective of an external application. As a result, some minor tweaks were made around error reporting. Potentially a refactor of the mietter::Diagnostic stuff in this PR will be included in the parser crate in the future.
It currently accepts no commands, assuming any/all input is a PartiQL query, which it will attempt to parse. Parse errors are pretty printed to the output.
This uses:
- [miette](https://crates.io/crates/miette) for errors
- [rustyline](https://crates.io/crates/rustyline) for readline/editing/history
- [syntect](https://crates.io/crates/syntect) for syntax highlighting via the included sublime …
=> Experimental REPL PoC

partiql-conformance-test-generator/src/generator.rs, partiql-conformance-test-generator/src/lib.rs, partiql-conformance-test-generator/src/schema.rs
Updates the conformance test runner following https://github.com/partiql/partiql-tests/pull/18 and some other commits, which
- updated the test schema (i.e. `parse` -> `syntax`, `semantic` -> `static analysis` and remove test annotation)
- added some data/time tests
- moved some `IN` clause tests from `syntax` to `static analysis`
Due to the updated test schema, I had to update the parsing of the test data. I also did a slight refactor of the test data schema objects and the test generator.
=> Update git submodule following conformance refactor; refactor schema objects + generation

partiql-parser/src/lexer.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
*Issue #, if available:* #137 #108 
- Fix parsing for path whildcard and array with a dot
This change fixes parsing of expressions like the following:
`foo(x, y)[*].*.b[5]`
In the above expression a `.` follows a path whildcard
- Add `TABLE` keyword
This is to ensure the following syntax conformance test passes:
```rust
fn invalid_path_component_keyword_in_path_test() {
let statement = r#"SELECT foo.id, foo.table FROM `[{id: 1, table: "foos"}]` AS foo"#;
let res = partiql_parser::Parser::default().parse(statement);
assert!(
res.is_err(),
"For `{}`, expected `Err(_)`, but was `{:#?}`",
statement,
res
);
```
=> Fix parsing for dot following arr and [*] path and add `TABLE` keyword

partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/parse_util.rs, partiql-parser/src/parse/partiql.lalrpop
e.g., when parsing `((4/2)+(7*7)-2)`
=> Strip `ast::Query` when it only encloses a `ast::Expr`

.github/workflows/ci_build_test.yml, .github/workflows/coverage.yml, Cargo.toml, partiql-ast/Cargo.toml, partiql-ast/src/ast.rs, partiql-ast/src/lib.rs, partiql-cli/Cargo.toml, partiql-conformance-test-generator/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-parser/Cargo.toml, partiql-parser/src/error.rs, partiql-parser/src/lib.rs, partiql-playground/Cargo.toml, partiql-source-map/Cargo.toml, partiql-source-map/src/line_offset_tracker.rs, partiql-source-map/src/location.rs
- Make usage of `serde` optional behind feature flag `serde`
- exclude CLI and playground from main workspace
- use more broadly compatible version requirement for `serde`
---
=> Make usage of `serde` optional behind feature flag `serde`

partiql-ast/src/ast.rs, partiql-parser/src/parse/partiql.lalrpop
- remove redundant `CaseSensitivity`
- treat `in` more like a binary operator
=> Minor AST refactor

.github/workflows/ci_build_test.yml, partiql-conformance-tests/src/bin/generate_comparison_report.rs
Also runs `cargo fmt --all` to cleanup minor style issues.
=> ci: adds --workspace to cargo fmt

partiql-ast/src/ast.rs, partiql-cli/src/visualize/ast_to_dot.rs, partiql-cli/src/visualize/render.rs, partiql-conformance-tests/src/bin/generate_comparison_report.rs, partiql-parser/src/lexer.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop, partiql-parser/src/preprocessor.rs
Cf #156 
#108 #149 
Ensure the following statements parse:
- TIME WITH TIME ZONE <string-literal>
- TIME(10) WITH TIME ZONE <string-literal>
- TIME WITHOUT TIME ZONE <string-literal>
- TIME (20) WITHOUT TIME ZONE <string-literal>
- CAST(a AS TIME)
- CAST(b AS TIME(10))
`cargo run  --features visualize -- ast -Tdisplay  "select time (10) with time zone '22:12', time (10) without time zone '22:12'"`:
---
*Note* that this also allows statements like the following to parse (we'll need to reject at type check):
- TIME(3) WITH(2) TIME(5) ZONE(TIME(WITHOUT(5))) '22:22:10'
`cargo run  --features visualize -- ast -Tdisplay  "TIME(3) WITH(2) TIME(5) ZONE(TIME(WITHOUT(5))) '22:22:10'"`:
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Parse SQL-style typed-literal strings

partiql-cli/Cargo.toml, partiql-conformance-test-generator/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-playground/Cargo.toml, partiql-source-map/Cargo.toml
#167 
Fixes `keywords` and `categories` in `Cargo.toml`; specifically it ensures the number `keywords` is less than or equal to 5, because a value more than that causes an issue in `cargo publish`.
=> Fix keywords and categories

partiql-conformance-tests/Cargo.toml
#166 
1. Remove PartiQL Playground `demo.gif`
```bash
cargo publish --dry-run && echo $?
warning: aborting upload due to dry run
0
cargo publish
...
error: failed to publish to registry at https://crates.io
Caused by:
the remote server responded with an error: max upload size is: 10485760
➜  partiql-playground git:(playgrond-size-reduce) ls -l target/package/partiql-playground-0.1.0.crate
-rw-r--r--  1 maymandi  staff  10273106 Aug  5 15:59 target/package/partiql-playground-0.1.0.crate
```
We could use `exclude` in `Cargo.toml` but I as what the file represents can get obsolete perhaps it's worthwhile to just remove it.
2. Fix version numbers in conformance tests packages.
By submitting this pull request, I confirm that my contribution is …
=> Fix v0.1.0

partiql-ast/Cargo.toml, partiql-cli/Cargo.toml, partiql-conformance-test-generator/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-irgen/Cargo.toml, partiql-parser/Cargo.toml, partiql-playground/Cargo.toml, partiql-rewriter/Cargo.toml, partiql-source-map/Cargo.toml, partiql/Cargo.toml
*Issue #, if available:* 
#166 
Prepares the version as pre-release for the next version.
```bash
cargo release --dev-version --no-push --no-publish -x
...
```
Since `partiql-cli` and `partiql-playground` are [excluded](https://github.com/partiql/partiql-lang-rust/blob/f99ce48dc3bb64571d80452c705b662302e6dfce/Cargo.toml#L15) from workspace, had to create a change for them manually. For `partiql-playground` we don't intend to release as there is no entry-point to it at this stage. For `partiql-cli` we probably need to include it as workspace `members` so that it can get included in the release. For now I'm adding the change for both until we finalize the decision for the next release.
By submitting this pull request, I confirm that my contribution is made under …
=> (cargo-release) start next development iteration 0.1.1-alpha.0

Cargo.toml, partiql-ast/Cargo.toml, partiql-cli/Cargo.toml, partiql-conformance-test-generator/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-irgen/Cargo.toml, partiql-parser/Cargo.toml, partiql-playground/Cargo.toml, partiql-rewriter/Cargo.toml, partiql-source-map/Cargo.toml, partiql/Cargo.toml
#166 
- Moves the following pacakges to workspace excluded:
- "partiql-conformance-test-generator"
- "partiql-conformance-tests"
For both, users can play around with conformance tests using GitHub code.
- Removes [workspace] attribute from `partiql-cli` `Cargo.toml`. This is
does not seems to be affect partiql-cli build.
- Changes the version back to "0.1.0". This seems to be more aligned with
other projects as noted by @alancai98 before.
=> Fix pre-release

partiql-conformance-test-generator/src/generator.rs
Cleans up ~97 warnings in the conformance tests similar to
```
warning: unused variable: `statement`
--> partiql-conformance-tests/tests/partiql_tests/partiql_tests_data/fail/static_analysis/primitives/time_constructor.rs:166:9
|
166 |     let statement = r#"TIME WITH TIME ZONE (4) '23:59:59.99999'"#;
|         ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_statement
```
=> Allow `unused variables` in "Not Yet Implemented" tests

partiql-eval/benches/bench_eval.rs, partiql-eval/src/lib.rs, partiql-value/src/lib.rs
Clean up test & static data creation via creation and use of `partiql_tuple!` macro.
=> Add `partiql_tuple!` macro

partiql-ast/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-ir/Cargo.toml, partiql-irgen/Cargo.toml, partiql-parser/Cargo.toml, partiql-rewriter/Cargo.toml, partiql-source-map/Cargo.toml, partiql-types/Cargo.toml, partiql/Cargo.toml
Common Keys:
- authors
- homepage
- repository
- crate version
- rust edition
See
https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table
=> Use workspace inheritance for common keys in Cargo.toml for each crate in workspace

partiql-eval/Cargo.toml, partiql-eval/benches/bench_eval.rs, partiql-eval/src/env.rs, partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/Cargo.toml, partiql-logical/src/lib.rs, partiql-value/src/lib.rs
*Issue #, if available:* 
Closes #21
Adds the required changes for enabling query evaluation using a DAG model.
What is our definition of DAG?
We are only interested in DAGs that can be used as execution plans, which leads to the following definition. A DAG is a directed, cycle-free graph G = (V, E) with a denoted root node v0 ∈ V such that all v ∈ V \{v0} are reachable from v0. Note that this is the definition of trees without the condition |E| = |V | − 1. Hence, all trees are DAGs. Reference: https://link.springer.com/article/10.1007/s00450-009-0061-0
- The steel thread includes only `Scan` and `Project` operators, and passes the test for planning and evaluation of the following query:
```SQL
SELECT a AS b FROM data
```
- The code is _not_ clean, maybe not idiomatic at some instances, …
=> [steel thread] Add query plan and eval using DAG model

partiql-eval/Cargo.toml, partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs, partiql-value/Cargo.toml, partiql-value/src/lib.rs
Implements arithmetic ops (+, -, *, /, %; exponentiation is saved for a TODO) in the evaluator and adds a Decimal PartiQL `Value` using the [rust_decimal](https://crates.io/crates/rust_decimal) crate. Also included are some minor fixes to the following:
- Fix to `Ord` related to `OrderedFloat` behavior
- Add `missing`/`null` propagation in binary expressions
=> Add arithmetic ops to evaluator; add Decimal partiql-value

partiql-conformance-test-generator/Cargo.toml, partiql-conformance-test-generator/src/generator.rs, partiql-conformance-test-generator/src/lib.rs, partiql-conformance-test-generator/src/reader.rs, partiql-conformance-test-generator/src/schema.rs, partiql-conformance-test-generator/src/util.rs, partiql-conformance-test-generator/src/writer.rs, partiql-conformance-tests/Cargo.toml, partiql-conformance-tests/build.rs, partiql-source-map/Cargo.toml
This is a behavior-preserving refactor of conformance test generator library to encapsulate all generation logic. 
Logic is split into 3 phases:
- the reader reads the filesystem & ion test files into a set of schema structs
- the generator transforms the schema & structure into a tree of 'codegen' objects
- the writer creates directories, writes out the codegen objects, and generates rust module trees
---
Diff against previous version's generated output, showing identical generation:
```shell
❯ diff -C 1 -r tests tests_v0 -s
Files tests/mod.rs and tests_v0/mod.rs are identical
Files tests/partiql_tests/mod.rs and tests_v0/partiql_tests/mod.rs are identical
Files tests/partiql_tests/partiql_tests_data/fail/mod.rs and tests_v0/partiql_tests/partiql_tests_data/fail/mod.rs are identical …
```
=> Refactor conformance test generator to encapsulate logic

partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/Cargo.toml, partiql-logical/src/lib.rs
*Issue #, if available:* 
Closes #206
As a follow on action item from #202  this commit removes the `petgraph`
dependency from `LogicalPlan`.
The graph presented in this commit has just enough interfaces for doing
he work for now. We need to iterate on it later when vending as an API
to consumers.
=> Remove `petgraph` from logical plan dependency

partiql-conformance-test-generator/src/generator.rs, partiql-conformance-test-generator/src/reader.rs, partiql-conformance-test-generator/src/writer.rs
Move large "expected" values to external files similar to "environment" files.
Move all such test data files into `_test_data` directory.
---
=> For Conformance Test Generator: large epectations to file rather than inline string.

partiql-eval/Cargo.toml, partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs, partiql-value/src/lib.rs
Closes #216 
This commit adds the planning and evaluation of `SELECT VALUE` statements. It also:
- Addresses a previous comment with regards to adding `thiserror` to `EvaluationErr`.
- Adds `Debug` to `Tuple` type.
The following cases are covered in tests:
```SQL
-- Expected: <<2, 4, 6>>
SELECT VALUE 2*v.a
FROM [{'a': 1}, {'a': 2}, {'a': 3}] AS v;
```
```SQL
-- Expected: <<{'a': 1, 'b': 1}, {'a': 2, 'b': 2}>>
SELECT VALUE {'a':v.a, 'b':v.b}
FROM [{'a': 1, 'b': 1}, {'a': 2, 'b': 2}] AS v;
-- Treatment of mistyped attribute names
-- Expected: <<{'legit': 1}, {}>>
SELECT VALUE {v.a: v.b}
FROM [{'a': 'legit', 'b': 1}, {'a': 400, 'b': 2}] AS v;
-- Treatment of duplicate attribute names
-- Expected: <<{'same': 1, 'same': 2}>>
SELECT VALUE {v.a: …
```
=> Add `SELECT VALUE` planning and evaluation

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs
Adds `INNER` and `CROSS JOIN`s to planner and evaluator, which required adding a branch side tracking to the DAG.
Still have some TODOs to address but wanted to cut this PR before working on those.
- `LATERAL` `JOIN`s
- Cleanup of `.clone()`ing
- `LEFT JOIN`s
=> Add `INNER` and `CROSS JOIN`s to planner and evaluator

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs, partiql-value/src/lib.rs
This PR:
- Fixes comparison ops (`<`, `>`, `<=`, `>=`). Previously didn't properly handle data type mismatches (returned boolean rather than missing)
- Adds `BETWEEN` op (e.g. `foo BETWEEN 1 AND 2`)
- Changes some PartiQL `Value` extension methods to operate on reference to `Value`s rather than `Value`s
- Some minor bug fixes from previous comparison implementation
=> Fix comparison ops, add between op

partiql-parser/src/lexer.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/preprocessor.rs
- Relevant to #221 
- Adds tests to assert that the current identifiers of `acyclic`, `both`, `domain`, `public', `user`, `leading`, `trail`, and `trailing` are lexed and parsed as identifiers.
- Specifically adds more comprehensive testing to the preprocessor to add testing related to the use of the trim specification keywords.
=> Expands parser/lexer tests to test future possible keywords

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs
Closes #219
This commit adds the required changes to implement `IN` expression. The following test passes:
```SQL
SELECT a AS b FROM [{'a': 1}, {'a': 2}, {'a': 3}] WHERE a IN [1];
-- Expected << {'b': 1} >>
```
=> Implement `IN` expr

partiql-eval/benches/bench_eval.rs, partiql-eval/src/env.rs, partiql-eval/src/eval.rs, partiql-value/src/lib.rs
Refactors `JOIN`s (Cf. #218) to use fewer `clone()`s. 
Adds to `Value`:
- coercions to Tuple, Bag, and List that do not require taking ownership of the value
- `iter()` for Tuple, Bag, and List and corresponding `Iterator` implementations over the reference values
- `FromIterator` implementations for Tuple, Bag, and List to allow `collect()`ing into them from iterators
---
=> Refactors JOINs to use fewer clone()s.

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs, partiql-value/src/lib.rs
Note: target branch is `case-expressions`. Will create a new PR targeting `main` once that branch's PR (#228) is merged to `main`.
*Issue #, if available:* None.
*Description of changes:* Implements `IS` (unknown types only -- i.e. `IS [NOT] NULL` and `IS [NOT] MISSING`), `NULLIF`, and `COALESCE`. `NULLIF` and `COALESCE` are implemented using the rewrites mentioned in the SQL-92 spec (section 6.9, pg 142).
=> Implements `IS` (unknown types only), `NULLIF`, and `COALESCE`

partiql-eval/benches/bench_eval.rs, partiql-eval/src/env.rs, partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs, partiql-value/src/lib.rs
Note: target branch is `feat-value-iters`. Will create a new PR targeting `main` once that branch's PR is merged to `main`.
*Issue #, if available:* None.
*Description of changes:* Adds simple and searched case when expressions to the evaluator. Also fixes projection behavior when a tuple value is `MISSING` (previously included those tuple values; now omits).
=> Add simple and searched case when expressions to evaluator

partiql-conformance-test-generator/src/generator.rs, partiql-conformance-tests/Cargo.toml, partiql-conformance-tests/tests/mod.rs, partiql-conformance-tests/tests/test_value.rs
Add PoC parsing of conformance test values encoded in ion
---
=> Add PoC parsing of conformance test values encoded in ion

partiql-eval/benches/bench_eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs
In addition
- re-organizes the code in `partiql-logical/src/lib.rs`.
- renames `BindingsExpr` to `BindingsOp` to reflect the fact that the related variants are operators on binding expressions.
=> Add `LogicalPlan` documentation and some clean-up

partiql-conformance-tests/src/bin/generate_comparison_report.rs, partiql-conformance-tests/src/bin/generate_cts_report.rs, partiql-parser/src/lexer.rs, partiql-value/src/lib.rs
*Issue #, if available:* None
*Description of changes:* Some clippy warnings were causing a lot of noise in PRs. Fixed some clippy warnings in this PR.
=> Fix clippy warnings in partiql-value, partiql-parser, partiql-conformance-tests

partiql-ast/src/ast.rs, partiql-parser/src/parse/parser_state.rs, partiql-parser/src/parse/partiql.lalrpop
Don't wrap `FromSource` in `AstNode` in AST
The `AstNode` is extraneous when trying to manipulate/inspect the AST.
---
=> Don't wrap `FromSource` in `AstNode` in AST

partiql-eval/benches/bench_eval.rs, partiql-eval/src/env.rs, partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-logical/src/lib.rs, partiql-value/src/lib.rs
- Fixes some TODO's related to `Bindings` and `Tuple` case insensitivity
- Make `PathComponent`'s `Key` `BindingName` rather than a `String`
- Updates some benchmark code
- Makes `Tuple`'s `vals` field private
=> Address binding case insensitivity TODOs; make PathComponent's Key BindingName rather than String

partiql-conformance-test-generator/src/generator.rs, partiql-conformance-tests/Cargo.toml, partiql-conformance-tests/tests/mod.rs, partiql-conformance-tests/tests/test_value.rs, partiql-value/src/lib.rs
- eval tests fail with a `todo()`
- also fixes some bugs with embedded environements in test generation
---
=> Stop ignoring evaluation conformance tests.

.github/workflows/coverage.yml
Conformance tests are run with 'conformance_test' feature. Since the code coverage GH Actions step runs with 'all-features', the conformance test are also run, which can cause `cargo test` to fail. Add 'continue-on-error' step to prevent GH Actions failure.
=> Add 'continue-on-error: true' to coverage step

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs
Models a query that is entirely an expression, such as `2+2` or `table.a *10`
---
=> Add ExprQuery BindingsOp

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs
=> Fix handling of `NULL`/`MISSING` in short circuit of `AND` and `OR`

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs
Add `ProjectAll` for use in `SELECT *`
`SELECT *` is currently underspecified w.r.t. nested data, but this is at least a first cut at non-join results.
---
=> Add `ProjectAll` for use in `SELECT *`

partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical/src/lib.rs
e.g. `[1,2,3][1+1]` <=> `[1,2,3][2]` <=> `3`
=> Add ability to use `EvalExpr` in path components

partiql-conformance-tests/src/bin/generate_comparison_report.rs
Previously if a PR, fixed or renamed a bunch of conformance tests, the conformance report comment in the PR would have a long list of failing tests.
(above taken from https://github.com/partiql/partiql-lang-rust/pull/257#issuecomment-1371531091 and lists about 900 tests)
Changed to hide behind a "Summary" link that can be clicked to expand:
(above taken from https://github.com/partiql/partiql-lang-rust/pull/253#issuecomment-1362213443, in which I altered the comment to include this PR's changes)
=> Make tests in conformance report GH comment collapsible

partiql-eval/src/eval.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/call_defs.rs, partiql-logical-planner/src/lib.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql-parser/src/preprocessor.rs, partiql-value/src/lib.rs
Function call lowering and evaluation for selected built-ins:
- char_len
- lower
- upper
- substring
- trim
- coalesce
- nullif
---
=> Function call lowering and evaluation for selected built-ins

partiql-value/src/lib.rs
Coerce MISSING to `{}`, not `{ '_1': MISSING }`
---
=> FIX: Coerce MISSING to an empty tuple

partiql-ast/src/ast.rs, partiql-eval/src/eval.rs, partiql-eval/src/plan.rs
Adds documentation for Evaluator. It also:
- Renames `EvalProjectValue` to `EvalSelectValue` to better conform to PartiQL core naming.
- Fixes `partiql-ast` documentation.
=> Add documentation for Evaluator and minor fix for ast doc.

CHANGELOG.md, Cargo.toml, partiql/Cargo.toml, partiql/benches/bench_eval_multi_like.rs
Tests ported from https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/jmh/kotlin/org/partiql/jmh/benchmarks/MultipleLikeBenchmark.kt
---
=> Add benchmarks to parse,compile,plan,eval for 1,15,30 `OR`ed `LIKE`s

partiql-parser/Cargo.toml, partiql-parser/src/parse/mod.rs, partiql-parser/src/preprocessor.rs
`lazy_static` is old and relies on macros.
`OnceCell` uses more modern rust features and its API is under consideration for inclusion in `std` (See rust-lang issue 74465).
---
=> Replace usages of lazy_static with once_cell

.github/workflows/ci_build_test.yml, deny.toml
Run cargo-deny check and report.
Fails if any of the following are found used in the crate or its dependencies.
- any banned crates
- disallowed open source licenses
- use of disallowed repository sources
Reports, but does not fail on (to prevent sudden announcement of a new advisory from failing ci):
- security advisories
See:
- https://github.com/EmbarkStudios/cargo-deny
- https://embarkstudios.github.io/cargo-deny/index.html
- https://github.com/EmbarkStudios/cargo-deny-action
=> Add cargo-deny config and CI action to enforce it

about.toml, deny.toml
Add configuration for `cargo-about`
See https://embarkstudios.github.io/cargo-about/index.html
---
=> Add configuration for `cargo-about`

partiql-eval/src/eval.rs, partiql-eval/src/plan.rs, partiql-parser/src/parse/parser_state.rs
Improve performance by removing extraneous `clone`s and tweaking initial buffer sizes.
```
10:38❯ cargo bench
Finished bench [optimized + debuginfo] target(s) in 0.68s
Running benches/bench_eval_multi_like.rs (target/release/deps/bench_eval_multi_like-40a62f267e10d031)
parse-1                 time:   [6.7670 µs 6.8086 µs 6.8564 µs]
change: [-8.6514% -7.1434% -5.6991%] (p = 0.00 < 0.05)
Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
7 (7.00%) high mild
1 (1.00%) high severe
parse-15                time:   [58.581 µs 58.882 µs 59.206 µs]
change: [-4.1975% -2.8944% -1.4224%] (p = 0.00 < 0.05)
Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
2 (2.00%) high mild
5 (5.00%) high severe
parse-30                time:   [118.08 µs 118.62 µs 119.16 …
```
=> Improve performance by removing extraneous `clone`s and tweaking initial buffer sizes.

.github/workflows/benchmark.yml, .github/workflows/ci_build_test.yml, .github/workflows/coverage.yml
- Update still-supported actions to versions that don't use deprecated features
- Replace  `actions-rs/toolchain` with `dtolnay/rust-toolchain`
- Updates our conformance report commenting to not use `set-output`
- replace `clippy-check`
Node.js 12 actions and `set-output` are deprecated.
See:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Also, The `actions-rs` actions appear unmaintained:
- https://github.com/actions-rs/toolchain/issues/216
Compare warning annotations for:
- old: https://github.com/partiql/partiql-lang-rust/actions/runs/4001004554
- new: https://github.com/partiql/partiql-lang-rust/actions/runs/400 …
=> Update CI actions

CHANGELOG.md, partiql-eval/src/eval.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs
Implements `PIVOT` operator in evaluator. Defined in section [6.2 of PartiQL spec](https://partiql.org/assets/PartiQL-Specification.pdf#subsection.6.2).
---
=> Implement `PIVOT` in evaluator

partiql-ast/partiql-ast-macros/src/lib.rs, partiql-ast/src/ast.rs, partiql-conformance-test-generator/src/generator.rs, partiql-conformance-tests/tests/mod.rs, partiql-conformance-tests/tests/test_value.rs, partiql-eval/src/env.rs, partiql-eval/src/eval.rs, partiql-eval/src/lib.rs, partiql-logical-planner/src/lower.rs, partiql-parser/src/lexer.rs, partiql-parser/src/preprocessor.rs, partiql-source-map/src/location.rs, partiql-value/src/ion.rs, partiql-value/src/lib.rs, partiql/benches/bench_eval_multi_like.rs
The recent Rust toolchain upgrade PR https://github.com/partiql/partiql-lang-rust/pull/285 brought in a new Rust version, which shows a lot more clippy warnings. This PR just runs `cargo clippy --fix` to fix those warnings.
Mostly dealt with the following warning:
- variables can be used directly in the `format!` string (https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args)
---
=> Fix clippy warnings following GH Actions Rust version bump

partiql-conformance-tests/src/bin/generate_comparison_report.rs, partiql-conformance-tests/src/bin/generate_cts_report.rs, partiql-eval/src/eval.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs
(Additional LIKE tests are in pending partiql-tests PR: https://github.com/partiql/partiql-tests/pull/49. Once that's merged, will update the partiql-tests submodule).
Implements `LIKE` for non-string, non-literals. Previous implementation only accounted for scenario in which `LIKE` was given non-string, non-literal arguments. This resulted in some queries given NULL or MISSING pattern or escape arguments to fail an assertion while lowering to the logical plan.
Remaining TODOs:
=> Implement `LIKE` for non-string, non-literals

CHANGELOG.md, partiql-value/Cargo.toml, partiql-value/src/lib.rs
Adds the `serde-json`'s `Serialize` and `Deseralize` to `partiql_value::Value` as a feature.
=> Add Serde json

CHANGELOG.md, partiql-logical/Cargo.toml, partiql-logical/src/lib.rs
Adds `serde` w/ `Serialize` and `Deserialize` traits to `partiql-logical`.
=> Add serde to partiql-logical

CHANGELOG.md, partiql-value/src/ion.rs, partiql-value/src/lib.rs
Make `partiql_value::parse_ion` public.
=> Make partiql_value::parse_ion  public

partiql-logical-planner/src/lower.rs
=> Fix off by one error when checking preconditions to lower join `ON`

partiql-ast/src/ast.rs, partiql-parser/src/parse/parse_util.rs, partiql-parser/src/parse/parser_state.rs, partiql-parser/src/parse/partiql.lalrpop, partiql-parser/src/preprocessor.rs
e.g., for `SELECT SUM(x) ...`,  `SUM` used to be parsed into a `ast::Call`, but will now be parsed into a `ast::CallAgg`
---
=> Recognize aggregate fn names in parser

partiql-parser/src/parse/partiql.lalrpop
Cf. https://github.com/partiql/partiql-tests/blob/066da8fd11c5292245121e2e59a7df5735e58603/partiql-tests-data/eval-equiv/spec-tests.ion#L467
---
=> Make `BY <x>` optional in `GROUP` clause

partiql-parser/src/parse/partiql.lalrpop
=> Fix `JOIN` parsing: Default to `INNER`; Allow ellision of keywords.

partiql-parser/src/parse/partiql.lalrpop
Cf. https://github.com/partiql/partiql-tests/blob/29c49b9ad61aee4fc38344f3855ee1c935ee7dd1/partiql-tests-data/eval/primitives/aggregate-function-call.ion#L201
---
=> Allow un-parenthesized subquery as the only argument of a function

partiql-ast/src/ast.rs, partiql-ast/src/visit.rs, partiql-ast/tests/test_ast.rs, partiql-parser/src/lexer.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/parse_util.rs, partiql-parser/src/parse/partiql.lalrpop
Cf. https://github.com/partiql/partiql-tests/blob/4ab01b3ffa8c0ebf3bae0697111b42714f22a544/partiql-tests-data/eval/spec-tests.ion#L744
Cf. https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#with-clause
---
=> Add parsing of `WITH` clause (`SEARCH` & `CYCLE` still TODO)

.gitmodules, CHANGELOG.md, partiql-ast/src/ast.rs, partiql-ast/src/visit.rs, partiql-ast/tests/test_ast.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql-parser/src/parse/parse_util.rs, partiql-parser/src/parse/partiql.lalrpop
- Merges `Limit` and `Offset` into one `LimitOffsetClause` AST node
- Adds `EvalLimitOffset` evaluator operator
- Updates parser and lowering to evaluator
- Updates changelog
---
=> Add `LIMIT` and `OFFSET` operators to evaluator

partiql-logical-planner/Cargo.toml, partiql-logical-planner/src/call_defs.rs, partiql-logical-planner/src/lower.rs
fixes #317 
for `cargo bench compile`:
before:
```
compile-1               time:   [26.914 µs 27.030 µs 27.158 µs]
change: [-1.4509% -0.1010% +1.2654%] (p = 0.88 > 0.05)
No change in performance detected.
Found 5 outliers among 100 measurements (5.00%)
3 (3.00%) high mild
2 (2.00%) high severe
compile-15              time:   [71.181 µs 71.398 µs 71.624 µs]
change: [+0.3953% +1.1365% +1.8644%] (p = 0.00 < 0.05)
Change within noise threshold.
Found 9 outliers among 100 measurements (9.00%)
7 (7.00%) high mild
2 (2.00%) high severe
compile-30              time:   [122.76 µs 123.42 µs 124.27 µs]
change: [-0.4880% +0.2882% +1.0441%] (p = 0.48 > 0.05)
No change in performance detected.
Found 9 outliers among 100 measurements (9.00%)
4 (4.00%) high mild
5 (5.00%) high severe
```
after:
``` …
```
=> Only construct FnSymTab once, using `OnceCell`

CHANGELOG.md, partiql-value/src/lib.rs, partiql-value/src/tuple.rs
Tuple value equality was wrong in the case of duplicates and different tuple orders. Tuple value hashing was also wrong for unordered nested values.
Test cases in this PR show the correct behavior but were all previously failing.
=> Fix Tuple value duplicate equality and hashing

CHANGELOG.md, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical-planner/src/name_resolver.rs, partiql-logical/src/lib.rs, partiql-value/src/datetime.rs, partiql-value/src/lib.rs
Provides the initial implementation of `GROUP BY ... GROUP AS ...` bindings expression. Fixes about 60+ `GROUP BY` conformance tests. Remaining failing conformance tests are due to:
- Unimplemented `HAVING` clause https://github.com/partiql/partiql-lang-rust/issues/326
- Unimplemented aggregation functions https://github.com/partiql/partiql-lang-rust/issues/327
- `SELECT *` used with `GROUP BY`
- Spec behavior is unclear on `SELECT *` with `GROUP BY` and current `SELECT *` is buggy
- Plan to update those tests to not use `SELECT *`. These tests pass if `SELECT`ing on the `GROUP BY` aliases explitly
- Some tests where the `GROUP` value contains `MISSING` but not `NULL` https://github.com/partiql/partiql-lang-rust/issues/328
- Unimplemented `CAST` function …
=> Add initial GROUP BY implementation

partiql-ast/src/ast.rs, partiql-ast/src/visit.rs, partiql-logical-planner/src/lower.rs, partiql-parser/src/parse/partiql.lalrpop
Adds parser and AST support for `TABLE <id>` query expressions
---
=> Parse `TABLE <id>` references

CHANGELOG.md, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs
Implements lowering & evaluation of `ORDER BY` clause.
Some `ORDER BY` conformance tests still fail due to a lack of proper name resolution and data flow analysis, which will be addressed separately.
---
=> Implements `ORDER BY`

CHANGELOG.md, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql-value/src/lib.rs
Implements SQL aggregation functions (AVG, COUNT, MAX, MIN, SUM) in the evaluator.
Performs some rewrites:
- SQL aggregations without `GROUP BY` are rewritten to include a `GROUP BY true AS $__gk`
- SQL aggregations are rewritten to be computed in the GROUP BY
- E.g. `SELECT a, SUM(b) FROM t GROUP BY a` -> `SELECT a, $__agg_1 FROM t GROUP BY a`
- GROUP BY expressions usable by other clauses (e.g. SELECT list) for SQL compatibility https://partiql.org/assets/PartiQL-Specification.pdf#subsubsection.11.2.1
- E.g. `SELECT t.a + 1 AS a FROM t GROUP BY t.a + 1 AS some_group_alias` -> `SELECT some_group_alias AS a FROM t GROUP BY t.a + 1 AS some_group_alias`
---
- Some remaining test failures
- COUNT(*)
- ~NULL/MISSING in GROUP BY values https://github.com/partiql/partiql-lang-rust/issues/328~ …
=> Add initial sql call aggregation function implementation

CHANGELOG.md, partiql-conformance-tests/tests/test_value.rs, partiql-eval/src/eval/expr/mod.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/call_defs.rs, partiql-logical/src/lib.rs, partiql-parser/src/preprocessor.rs, partiql-value/src/datetime.rs, partiql-value/src/ion.rs, partiql-value/src/lib.rs
Implements `EXTRACT` builtin function and updates to the latest `partiql-tests`. Also fixes some parsing of the datetime part for `YEAR`, `TIMEZONE_HOUR`, and `TIMEZONE_MINUTE`. Makes the following assumptions:
- `EXTRACT` with a date component (year, month, day) on a time -> returns missing
- `EXTRACT` with a time component (hour, minute, second) -> returns missing
- a timezone part (timezone_hour, timezone_minute) with a datetime value without a timezone?
All of the above assumptions aren't specified in any SQL spec to my knowledge. The second assumption differs from what `partiql-lang-kotlin` currently does (which defines a default of `0`). Created a spec issue to track: https://github.com/partiql/partiql-spec/issues/53 along with a conformance test issue: …
=> Add EXTRACT builtin function; update `partiql-tests`

CHANGELOG.md, partiql-eval/benches/bench_eval.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/mod.rs, partiql-eval/src/plan.rs
Fixes https://github.com/partiql/partiql-lang-rust/issues/341.
Changes the visibilities of all the `EvalExpr` and `Evaluable` to be `pub(crate)`. PR also
- Changes usage of `EvalScan` and some `EvalExpr`s in eval benchmarking to use the logical plan equivalent
- Renames the eval aggregations to not use the same prefix (clippy warning)
- Fixes logical plan to eval plan conversion of `EvalOrderBySortSpec` with `DESC` and `NULLS LAST`
---
=> Change partiql-eval type visibilities

CHANGELOG.md, partiql-parser/src/preprocessor.rs
Fixes #343.
`TIME WITH TIME ZONE` literal values can be parsed normally but when within an `EXTRACT` function call, the parser gives an error:
```
parse: ParserError { text: "EXTRACT(HOUR FROM TIME WITH TIME ZONE '01:23:45.678') = 1", offsets: LineOffsetTracker { line_starts: [ByteOffset(0)] }, errors: [UnexpectedToken(Located { inner: UnexpectedTokenData { token: "FROM" }, location: Location { start: BytePosition(ByteOffset(13)), end: BytePosition(ByteOffset(17)) } })] }
```
=> Fix parsing of EXTRACT to allow keywords after the FROM

CHANGELOG.md, partiql-ast/partiql-ast-macros/src/lib.rs, partiql-ast/src/ast.rs, partiql-ast/src/visit.rs, partiql-conformance-tests/tests/mod.rs, partiql-logical-planner/Cargo.toml, partiql-logical-planner/src/error.rs, partiql-logical-planner/src/lib.rs, partiql-logical-planner/src/lower.rs, partiql-logical-planner/src/name_resolver.rs, partiql/benches/bench_eval_multi_like.rs
Partially addresses #349.
Changes the AST to logical plan `lower` function to return a `Result` type. This is part of an effort to reduce the `panic`s within the APIs. Also changes the `Visitor` API provided by `partiql-ast` to return a `Recurse` enum indicating whether visitation into the child nodes should continue or stop.
Conformance test changes are due to updating the `partiql-tests` commit.
=> Change `lower` to return `Result` rather than `panic`

partiql-logical-planner/src/error.rs, partiql-logical-planner/src/lower.rs
Follow on to #361 and #362 to make sure ion parsing returns `Result` rather than panicking
---
=> Modify `parse_embedded_ion_str` to return `Result`, not `expect()`

partiql-logical-planner/src/call_defs.rs, partiql-logical-planner/src/error.rs, partiql-logical-planner/src/lower.rs
AST to logical plan lowering would panic when an incorrect number of arguments was provided to the function. Changed in this PR to return a `Result` type for this case.
Also changes the recovery behavior to add a `Missing` literal to the environment stack to prevent some downstream irrelevant errors.
=> Change AST to logical plan function argument lowering to return Result

partiql-parser/Cargo.toml, partiql-parser/src/parse/mod.rs
Upgrades lalrpop to v0.20. Required a very small code change. Changes in lalrpop v0.20: https://github.com/lalrpop/lalrpop/blob/master/RELEASES.md#0200-2023-05-02
Main benefit/feature seems to be:
> faster compilation time by up to 2x
which should help w/ the current build times.
=> Update lalrpop to v0.20

CHANGELOG.md, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/mod.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/builtins.rs, partiql-logical/src/lib.rs, partiql-parser/src/parse/parser_state.rs
Implements the `COLL_` functions (`COLL_AVG`, `COLL_COUNT`, `COLL_MAX`, `COLL_MIN`, `COLL_SUM`). Also
- Fixes slight bug in the aggregation function regex
- Upgrades lalrpop to latest version to get rid of warnings
=> Adds the COLL_* functions (COLL_AVG, COLL_COUNT, COLL_MAX, COLL_MIN, COLL_SUM)

CHANGELOG.md, partiql-conformance-tests/tests/mod.rs, partiql-eval/benches/bench_eval.rs, partiql-eval/src/error.rs, partiql-eval/src/eval/mod.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lib.rs, partiql/benches/bench_eval_multi_like.rs
Part of #349.
Changes the logical to eval plan lowering API to use a `Result` type rather than panicking on errors. Other evaluation APIs will be changed in an upcoming PR.
=> Changes logical plan to eval plan API to return `Result` type

CHANGELOG.md, extension/partiql-extension-ion-functions/src/lib.rs
=> IonExtension is intended to be `pub`

CHANGELOG.md, Cargo.toml
release v0.4.1 to make `IonExtension` `pub`
command run:
```
cargo release patch --no-publish --no-push -x
```
=> chore: Release v0.4.1

CHANGELOG.md, partiql-eval/src/error.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/mod.rs, partiql-eval/src/eval/mod.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs
Should close out #349. Removes the panics in `EvalExpr` and `Evaluable` and allows for multiple error logging. Current implementation stores the errors in `EvalContext` and updates using interior mutability.
Additionally, changes the `Evaluable` trait's method `evaluate` to return a `Value` rather than an `Option<Value>`, since the optionality of the output value wasn't used anywhere.
=> Remove panics in `EvalExpr`, `Evaluable`, and `execute_mut`

.github/workflows/ci_build_test.yml, .github/workflows/coverage.yml
Should close out #364.
Similar to what was done in `ion-rust`: https://github.com/amazon-ion/ion-rust/pull/538. Makes some adjustments due to some conformance tests failing and using a different rust GH Actions.
=> Update codecov CI to stable version of Rust

partiql-eval/src/plan.rs, partiql-logical/src/lib.rs
=> Add `operators_by_id` to Logical Plan to get Nodes and their OpId

CHANGELOG.md, partiql-ast/src/ast.rs, partiql-logical-planner/src/lower.rs, partiql-parser/Cargo.toml, partiql-parser/src/parse/parse_util.rs, partiql-parser/src/parse/partiql.lalrpop
- Tracks synthesized attributes during parse (currently only whether sub-tree is all literal values)
- Translates literal sub-trees to `Value` literals during lowering
---
=> Translate collection literals to Value when lowering

Cargo.toml, partiql-ast-passes/Cargo.toml, partiql-ast-passes/LICENSE, partiql-ast-passes/src/error.rs, partiql-ast-passes/src/lib.rs, partiql-ast-passes/src/name_resolver.rs, partiql-conformance-tests/Cargo.toml, partiql-conformance-tests/tests/mod.rs, partiql-logical-planner/Cargo.toml, partiql-logical-planner/src/lib.rs, partiql-logical-planner/src/lower.rs
This PR is in preparation of upcomming work for adding an AST Typer. The name resolver seems to be required by the `typer` but it being in `partiql-logical-planner` implies its use only in planner.
In addition, this PR defines a new crate call `partiql-ast-passes` (could pick a better name and open to ideas)  that intends to include passes on AST transformation. Arguably `lower` in `partiql-logical-planner` can also be part of this new crate but leaving it out for now, as logical planning is a major transform and perhaps deserves its own crate.
* This PR also updates the `partiql-tests` sub-module.
=> Move `name_resolver` to a different crate

partiql-conformance-test-generator/src/generator.rs, partiql-conformance-tests/Cargo.toml, partiql-conformance-tests/README.md
This adds all existing test features as default, so running without specifying features works as it has:
```
cargo test --package partiql-conformance-tests --features "conformance_test" 
```
Which is equivalent to 
```
cargo test --package partiql-conformance-tests --no-default-features --features "base,conformance_test" 
```
But it also allows the ability to run subsets of the tests.
To run only `semantic` analysis tests:
```
cargo test --package partiql-conformance-tests --no-default-features --features "semantic,conformance_test" 
```
To run only `strict` tests:
```
cargo test --package partiql-conformance-tests --no-default-features --features "strict,conformance_test" 
```
To run `experimental` tests in addition to all default tests:
```
cargo test --package partiql-conformance-tests …
```
=> Add feature flags to conformance tests based on test type

partiql-ast/Cargo.toml, partiql-parser/src/lib.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/parser_state.rs, partiql-source-map/Cargo.toml, partiql-source-map/src/metadata.rs
Addressing the comment in PR #389, this PR re-uses the `AstTypeMap` for `LocationMap` which removes a dependency to `HashMap` as `AstTypeMap` uses `IndexMap`.
=> Use `partiql_ast::ast::AstTypeMap` for `LocationMap`

CHANGELOG.md, partiql-parser/src/parse/partiql.lalrpop
Fixes #403.
Fixes #404.
Fix the parsing of multiple, consecutive path wildcard (e.g. `a[*][*][*]`), unpivot (e.g. `a.*.*.*`), and path expressions (e.g. `a[1 + 2][3 + 4][5 + 6]`). Previously these would not parse correctly.
Points the `partiql-tests` git submodule to https://github.com/partiql/partiql-tests/pull/100 branch. Once that's merged, will rebase this PR to point to `partiql-tests` `main`.
=> Fix parsing of multiple consecutive path wildcard, unpivot, path expressions

partiql-parser/src/parse/partiql.lalrpop
Code refactor provided by @jpschorr who noticed some repetition in the lalrpop rule for `PathSteps`. Merging this can also help us check on the performance regression (https://github.com/partiql/partiql-lang-rust/commit/0f49d1b63f5743061eeebb94d9024a66f4efdb13#commitcomment-120867182) part of #405.
=> Slight refactor to PathSteps in grammar

CHANGELOG.md, partiql-logical-planner/src/lower.rs
`IN` expressions are currently part of AST parsing and logical/eval plan. The lowering from AST to logical plan hadn't been added yet.
=> Add AST to logical plan lowering for `IN` expressions

CHANGELOG.md, partiql-ast-passes/src/name_resolver.rs, partiql-ast-passes/src/partiql_typer.rs, partiql-ast/src/ast.rs, partiql-ast/src/visit.rs, partiql-eval/src/error.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/mod.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lib.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql-parser/src/lib.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/partiql.lalrpop
Implements the OUTER bag operators. Corrects a bug with the parsed set quantifier for bag operators. Previously when a set quantifier was unspecified, the default was `ALL`. Changed to be `DISTINCT`.
Other changes from this PR
- *BREAKING:* partiql-ast: rename of `SetExpr` to `BagOpExpr` and `SetOp` to `BagOp`
- Affects the AST and visitor
- *BREAKING:* partiql-parser: `Parsed` struct's `ast` field is now an `ast::AstNode<ast::TopLevelQuery>`
- *BREAKING:* partiql-eval: `Evaluable` trait's `update_input` fn now also takes in an `EvalContext`
- Closes #237. `branch_num` is now used for bag operators. Removed the comment for `add_flow_with_branch_num` fn.
=> Implements OUTER bag operators

CHANGELOG.md, partiql-eval/benches/bench_eval.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs
Changes the modeling of partiql-logical's `project` to be a `Vec` rather than a `HashMap`. Previously, couldn't include multiple project aliases with the same name.
For some context, some conformance tests that will be fixed in an upcoming PR are partially failing because the select list included multiple expressions with the same alias. 
=> Change modeling of project lists in logical plan

CHANGELOG.md, partiql-ast-passes/src/error.rs, partiql-eval/src/eval/eval_expr_wrapper.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/coll.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/builtins.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql-parser/src/parse/parser_state.rs, partiql-parser/src/preprocessor.rs, partiql-types/src/lib.rs
Adds the SQL aggregate functions `ANY`, `SOME`, and `EVERY` along with their `COLL_` versions (i.e. `COLL_ANY`, `COLL_SOME`, `COLL_EVERY`). 
This PR also
- fixes a slight bug related to the previously implemented SQL aggregates when an aggregation result is `NULL` or `MISSING`.
- closes #419 with some fixes to the strict mode type checking behavior of the `COLL_` functions.
- adds a check to logical plan lowering for `HAVING` without `GROUP BY`
=> Add SQL aggregates ANY, SOME, EVERY and their COLL_ versions

CHANGELOG.md, extension/partiql-extension-ion/src/decode.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/coll.rs, partiql-eval/src/lib.rs, partiql-value/src/bag.rs, partiql-value/src/lib.rs, partiql-value/src/list.rs, partiql-value/src/tuple.rs
- Implement `size_hint` for applicable iterators
- rename `coerce_to_*` methods to `coerce_into_*` when they take ownership
- reify some iterators rather than use `impl Iterator` 
---
=> Improvements to Value iterators

CHANGELOG.md, partiql-eval/src/eval/expr/operators.rs, partiql-value/src/bag.rs, partiql-value/src/lib.rs, partiql-value/src/list.rs, partiql-value/src/tuple.rs
Closes #420.
Previously, the `NullableEq` operator (i.e. `=`) wasn't performing deep equality on values within lists, bags, and tuples. PR adds the equivalent of the `eqg` function specified in [section 7.1.1](https://partiql.org/assets/PartiQL-Specification.pdf#subsubsection.7.1.1) which defines `NULL`s and `MISSING`s as equal. 
=> Fix list/bag/tuple deep equality

CHANGELOG.md, partiql-eval/benches/bench_eval.rs, partiql-eval/src/env.rs, partiql-eval/src/eval/expr/path.rs, partiql-eval/src/lib.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql-value/src/lib.rs, partiql-value/src/list.rs, partiql-value/src/tuple.rs
=> Change `BindingsName` to hold `Cow<str>` rather than  `String` to reduce `clone` needed for lookups

partiql-ast-passes/src/name_resolver.rs, partiql-logical-planner/src/lib.rs
During the work for adding a steel thread for PartiQL Typing (Recent PR #389) and after merging #410 to `feat-type-plan-poc` it is realized that we need to refactor the code to remove `DynamicLocalup` `VarExpr` with the assumption that we work based off of Typing and Value Environment from the Catalog. We have a Typing Environment in the Catalog at the moment and we are going to add the Variable Environment as well. In preparation for such task, we need to make the `NameResolver` Catalog aware. In that regard this commit adds the `Catalog` to `NameResolver`
Expecting subsequent PR(s) for the name resolving using the Catalog.
=> Add Catalog to NameResolver

CHANGELOG.md, partiql-catalog/src/call_defs.rs, partiql-logical-planner/src/lower.rs
Adds `COUNT(*)` lowering to `COUNT(1)`. Fixes a bug where a query with multiple aggregations without `GROUP BY` was only including the first aggregation.
=> Lower COUNT(*) to logical plan; fix multiple aggregations bug

partiql-eval/src/eval/eval_expr_wrapper.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/operators.rs, partiql-eval/src/eval/expr/path.rs, partiql-eval/src/eval/mod.rs, partiql-eval/src/plan.rs
Rendered Dot Graph Before:
Rendered Dot Graph After:
---
=> Write custom `Debug` for some parts of evaluator for better readability.

CHANGELOG.md, partiql-eval/Cargo.toml, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/plan.rs, partiql-value/src/bag.rs, partiql-value/src/lib.rs, partiql-value/src/list.rs, partiql/benches/bench_agg.rs
This rewrite removes duplicate effort by moving grouping state management in the EvalGroupBy rather than each individual aggregation function.
The group data is stored hashed by the values of the grouping expression (not yet bound to into a tuple, as the names don't add any discrimination to the grouping). 
The value stored at each group is:
- `state` for 'normal' aggregates
- `distinct_state` for distinct aggregates
- an extra `group_as` tuple if a `GROUP AS` clause is included.
Then, for each 'row' state is accumulated for aggregations, distinct aggregations, and group-as as appropriate.
After all 'rows' have been dealt with, then each group's aggregations, distinct aggregations, and group-as are finalized and every thing is wrapped up into a binding tuple.
- ~2x speedup on the simple …
=> Refactor `EvalGroupBy` and Aggregations to avoid duplicate effort

partiql-logical-planner/Cargo.toml, partiql-logical-planner/src/lower.rs
Currently during lowering, when we want to resolve a variable name we do the following:
1. If there are any `KeySchema`s  in `KeyRegistry` for the current `id` in the stack (lookup from bottom of the stack to the top)
2. Retrieve the `KeySchema`.
3. Lookup the `scopes` in `KeyRegistry` and see which `NodeId` this `Node` is within the scope of.
4. Get the `KeySchema` of the found `Node`.
5. If the variable name is equal to the `KeySchema`'s produce OR lowered case variable name is equal to `produce`'s lowered case and variable name is case-insensitive, then create a new `VarRef` with `Local` lookup and push it to the lookups (for `DynamicLookup`)
6. else create a `Path` with the `produce` name as `VarRef` and variable name as the key component.
This PR adds a step …
=> Add Catalog to resolve_varref in lowering

README.md, partiql-value/src/list.rs, partiql/benches/bench_agg.rs
Seems like GH Actions CI has been failing since a recent clippy change turned a warning into an error. PR also fixes a different clippy warning.
This should fix the GitHub Actions failure seen in https://github.com/partiql/partiql-lang-rust/pull/435.
=> Fix clippy warnings/errors

CHANGELOG.md, Cargo.toml, extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion/Cargo.toml, partiql-ast-passes/Cargo.toml, partiql-ast/Cargo.toml, partiql-catalog/Cargo.toml, partiql-conformance-tests/Cargo.toml, partiql-eval/Cargo.toml, partiql-logical-planner/Cargo.toml, partiql-logical/Cargo.toml, partiql-parser/Cargo.toml, partiql-source-map/Cargo.toml
Release for v0.6.0. Also makes slight edit to CHANGELOG ("Fixes" -> "Fixed").
Command run:
```
cargo release minor --no-publish --no-push -x
```
=> chore: Release v0.6.0

CHANGELOG.md, partiql-value/src/tuple.rs
None
This PR adds quotes to the attributes of a tuple to make the output compatible with Kotlin's `partiql-cli`.
Since some of the code is now ready, please allow me to also share with you our first use-case for PartiQL Rust.
In our case, our storage system would be FoundationDB (FDB). You can think of FDB as a distributed B-tree, similar to DynamoDB but with strict [ACID](https://apple.github.io/foundationdb/developer-guide.html#transactions-in-foundationdb) semantics. Similar to how DynamoDB provides attribute types, in FDB we have something called [Tuple layer](https://apple.github.io/foundationdb/data-modeling.html#data-modeling-tuples) (Note: FDB Tuple is semantically closer to PartiQL Array, and not a  PartiQL Tuple) .
The Tuple …
=> partiql-value: single quote tuple attribute

CHANGELOG.md, partiql-eval/src/eval/expr/path.rs, partiql-logical-planner/src/lower.rs, partiql/Cargo.toml, partiql/src/lib.rs
In certain cases (e.g., when `ORDER`ing by aggregates) `ORDER BY` couldn't access the fields created by projection.
For the command:
```
cargo run --release --all-features eval -f table "select foo, count(1) as n from
<<
{ 'foo': 'foo' },
{ 'foo': 'bar' },
{ 'foo': 'qux' },
{ 'foo': 'bar' },
{ 'foo': 'baz' },
{ 'foo': 'bar' },
{ 'foo': 'baz' }
>>  as data group by foo order by n asc"
```
Before:
```
+-----+---+
| foo | n |
+=========+
| bar | 3 |
|-----+---|
| qux | 1 |
|-----+---|
| foo | 1 |
|-----+---|
| baz | 2 |
+-----+---+
```
After:
```
+-----+---+
| foo | n |
+=========+
| qux | 1 |
|-----+---|
| foo | 1 |
|-----+---|
| baz | 2 |
|-----+---|
| bar | 3 |
+-----+---+
```
Fixes https://github.com/partiql/partiql-rust-cli/issues/25
---
By submitting this pull request, I confirm that …
=> Allow ORDER BY to 'see' projection names

Cargo.toml, extension/partiql-extension-visualize/src/ast_to_dot.rs, extension/partiql-extension-visualize/src/common.rs, extension/partiql-extension-visualize/src/plan_to_dot.rs, partiql-eval/src/eval/expr/path.rs
Clippy, Format, and other small cleanup.
---
=> Minor cleanup and formatting fixes

.github/workflows/ci_build_test.yml, CHANGELOG.md, Cargo.toml, extension/partiql-extension-ion-functions/src/lib.rs, partiql-catalog/src/context.rs, partiql-catalog/src/lib.rs, partiql-conformance-tests/tests/mod.rs, partiql-eval/Cargo.toml, partiql-eval/benches/bench_eval.rs, partiql-eval/src/env.rs, partiql-eval/src/error.rs, partiql-eval/src/eval/eval_expr_wrapper.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/base_table.rs, partiql-eval/src/eval/expr/control_flow.rs, partiql-eval/src/eval/expr/data_types.rs, partiql-eval/src/eval/expr/mod.rs, partiql-eval/src/eval/expr/operators.rs, partiql-eval/src/eval/expr/path.rs, partiql-eval/src/eval/expr/strings.rs, partiql-eval/src/eval/mod.rs, partiql-eval/src/lib.rs, partiql-logical-planner/src/lib.rs, partiql-logical-planner/src/lower.rs, partiql-value/src/datetime.rs, partiql/benches/bench_agg.rs, partiql/benches/bench_eval_multi_like.rs, partiql/src/lib.rs, partiql/tests/user_context.rs
Fixes #388 
Adds both a system-level and a user-level session context to the evaluation context. Also plumbs the context through to `BaseTableExpr` used in `partiql_catalog::Extension`s.
There is a lot of fiddly lifetime management and testing changes, as well as some slight trait refactors.
It's probably easiest to start with 
- the new integration test in `partiql/tests/user_context.rs` to see what kinds of things are possible,
- `partiql-catalog/src/context.rs` for the new context traits, and
- `partiql-eval/src/eval/mod.rs` for how it's used in evaluation.
---
=> Add session context to evaluation

CHANGELOG.md, partiql-catalog/src/context.rs, partiql-eval/src/env.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/mod.rs, partiql/src/lib.rs, partiql/src/subquery_tests.rs
1) Add subquery in `FROM` clause tests reference bindings
2) Fix subquery global binding lookup
3) Fix subquery error propagation
---
=>  Fix subquery global binding lookup and error propagation

CHANGELOG.md, Cargo.toml, partiql-logical-planner/src/typer.rs, partiql-types/src/lib.rs, partiql/src/subquery_tests.rs
partiql-types: Fixed handling of struct fields to be resilient to field order w.r.t. equality and hashing 
---
=> Use a BTreeSet for struct fields to assure stable hashing

CHANGELOG.md
=> chore: Release 0.7.2

partiql-catalog/src/lib.rs, partiql-eval/src/eval/eval_expr_wrapper.rs, partiql-eval/src/eval/expr/coll.rs, partiql-eval/src/eval/expr/operators.rs, partiql-logical-planner/src/lower.rs, partiql-logical-planner/src/typer.rs, partiql-types/Cargo.toml, partiql-types/src/lib.rs
Refactors `partiql-types` by adding `PartiqlShape`; with this model, `PartiqlShape`
is one of `Dynamic` (ex. `Any`), `AnyOf`, `Static`, or `Undefined`. `nullability` is
defined as part of `StaticType`.
One notable change in this PR is renaming the type `Any` to `Dynamic` to be more aligned with gradual typing taxonomy.
Apologies for the large diff.—it is as a result of the `PartiqlType` refactoring.
=> Add PartiQL Shape

.github/workflows/coverage.yml
As per https://docs.codecov.com/docs/adding-the-codecov-token
---
=> Add codecov token to CI

CHANGELOG.md, extension/partiql-extension-visualize/src/ast_to_dot.rs, partiql-ast-passes/src/name_resolver.rs, partiql-ast/Cargo.toml, partiql-ast/src/ast.rs, partiql-ast/src/lib.rs, partiql-ast/src/pretty.rs, partiql-ast/tests/common.rs, partiql-conformance-tests/Cargo.toml, partiql-conformance-tests/tests/mod.rs, partiql-logical-planner/src/lower.rs, partiql-parser/src/parse/partiql.lalrpop
Adds pretty-printing of ASTs. 
Currently ASTs pretty-print for all conformance tests that are currently parse-able except for those that use the `DISTINCT` set quantifier in the `SELECT` clause, though there are some minor formatting issues.
You can run the tests via 
```
cargo test --package partiql-conformance-tests --features "conformance_test, test_pretty_print"
```
~- [ ] Fix pretty-printing for `DISTINCT`~
~- [ ] Fix some minor formatting issues for `CASE`~
See #473
- *BREAKING:* partiql-ast: changed modeling of `BagOpExpr` `setq` field to be an `Option`
- *BREAKING:* partiql-ast: changed modeling of `GroupByExpr` `strategy` field to be an `Option`
- *BREAKING:* partiql-ast: changed modeling of `PathStep` to split `PathExpr` to `PathIndex` (e.g., `[2]`) and `PathProject` (e.g., …
=> Initial partial AST pretty-printer

CHANGELOG.md, partiql-ast/src/builder.rs, partiql-ast/src/lib.rs, partiql-parser/src/parse/mod.rs, partiql-parser/src/parse/parse_util.rs, partiql-parser/src/parse/parser_state.rs, partiql-parser/src/parse/partiql.lalrpop, partiql/src/subquery_tests.rs
This is mostly a refactor of existing functionality from the parser that moves it to the ast package and makes it public.
---
=> Add `NodeBuilder` for building ASTs

.gitmodules, CHANGELOG.md, extension/partiql-extension-ddl/src/ddl.rs, extension/partiql-extension-ddl/tests/ddl-tests.rs, partiql-ast/src/builder.rs, partiql-common/src/node.rs, partiql-eval/src/eval/eval_expr_wrapper.rs, partiql-eval/src/eval/expr/coll.rs, partiql-eval/src/eval/expr/datetime.rs, partiql-eval/src/eval/expr/operators.rs, partiql-eval/src/eval/expr/pattern_match.rs, partiql-eval/src/eval/expr/strings.rs, partiql-logical-planner/src/lower.rs, partiql-logical-planner/src/typer.rs, partiql-types/Cargo.toml, partiql-types/src/lib.rs
This PR
- adds `NodeId` to `StaticType`; this is to be able to use the `id` as a reference to add additional data to the types out of band.
- makes `AutoNodeIdGenerator` thread-safe
- adds `PartiqlShapeBuilder` and moves some `PartiqlShape` APIs to it; this is to be able to generate unique `NodeId`s for a `PartiqlShape` that includes static types that themselves can include other static types.
- adds a static thread safe `shape_builder` function that provides a convenient way for using `PartiqlShapeBuilder` for creating new shapes.
- prepends existing type macros with `type` such as `type_int!` to make macro names more friendly.
- removes `const` PartiQL types under `partiql-types` in favor of `PartiqlShapeBuilder`.
**_The majority of the diffs are related to the …
=> Adds `PartiqlShapeBuilder` with `NodeId` generation for the `StaticType`

partiql-types/src/lib.rs
Currently used in another project to output types like:
```
AnyOf(NOT NULL String, Int8, String, DateTime, String, Bool, String, AnyOf({value: Decimal(7,4), currency: String}, Decimal(3,2), Decimal(3,2), Decimal(4,2), Decimal(5,2)), {test_decimal: Decimal(3,0), test_string: String}, {nested_struct: {nested_struct: {nested_struct: {nested_struct: {nested_struct: {test_int: Int8}}}}}}),
```
---
=> Add more informational `Display` for `Static` types

partiql-types/src/lib.rs
=> Make it more ergonmic to use `PartiqlShapeBuilder` and type macros

extension/partiql-extension-ddl/Cargo.toml, extension/partiql-extension-ddl/src/ddl.rs, extension/partiql-extension-ion-functions/Cargo.toml, extension/partiql-extension-ion-functions/src/lib.rs, extension/partiql-extension-ion/Cargo.toml, extension/partiql-extension-ion/src/decode.rs, extension/partiql-extension-ion/src/encode.rs, extension/partiql-extension-ion/src/lib.rs, partiql-conformance-test-generator/Cargo.toml, partiql-conformance-test-generator/src/generator.rs, partiql-conformance-test-generator/src/reader.rs, partiql-conformance-test-generator/src/schema.rs, partiql-conformance-tests/Cargo.toml, partiql-conformance-tests/tests/test_value.rs, partiql-logical-planner/Cargo.toml, partiql-logical-planner/src/lower.rs, partiql-value/Cargo.toml
=> Rename `ion-rs` to `ion-rs_old` in preparation of upgrade

CHANGELOG.md, partiql-eval/src/eval/eval_expr_wrapper.rs, partiql-eval/src/eval/expr/functions.rs, partiql-eval/src/eval/expr/operators.rs, partiql-eval/src/lib.rs, partiql-value/src/lib.rs, partiql/tests/common.rs, partiql/tests/comparisons.rs, partiql/tests/extension_error.rs, partiql/tests/pretty.rs, partiql/tests/tuple_ops.rs, partiql/tests/user_context.rs
=> Add validation for comparison operations

partiql-conformance-test-generator/src/util.rs
Replace names 
- like: `strict_example_7_nu_l_l_and_missin_g_coercion_1`
- with: `strict_example_7_null_and_missing_coercion_1`
---
=> Lowercase before snake-casing for conformance test string escaping.

partiql-ast/src/ast.rs, partiql-ast/src/pretty.rs, partiql-logical-planner/src/lower.rs, partiql-parser/src/parse/parse_util.rs, partiql-parser/src/parse/partiql.lalrpop
Change parsing and AST-modeling of literals to not share AST structures with non-scalar expressions.
---
=> Change modeling of Literals in the AST remove ambiguity

CHANGELOG.md, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical-planner/Cargo.toml, partiql-logical-planner/src/builtins.rs, partiql-logical-planner/src/lower.rs, partiql-logical-planner/src/typer.rs, partiql-logical/Cargo.toml, partiql-logical/src/lib.rs, partiql-logical/src/util.rs, partiql-parser/src/parse/parse_util.rs, partiql/src/subquery_tests.rs
Changes the logical plan to have a distinct `Lit` type to hold literals instead of embedded `Value`
---
=> Change modeling of boxed ion literals to be lazy until evaluator.

.github/workflows/ci_build_test.yml, about.toml, deny.toml, extension/partiql-extension-ion/src/decode.rs, partiql-ast-passes/src/name_resolver.rs, partiql-eval/src/env.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/path.rs, partiql-eval/src/eval/mod.rs, partiql-logical-planner/src/functions.rs, partiql-logical-planner/src/lower.rs, partiql-parser/src/lexer/comment.rs, partiql-parser/src/lexer/embedded_ion.rs, partiql-parser/src/lexer/partiql.rs, partiql-parser/src/parse/parser_state.rs, partiql-types/Cargo.toml, partiql-types/src/lib.rs, partiql-value/src/bag.rs, partiql-value/src/lib.rs, partiql-value/src/list.rs, partiql-value/src/pretty.rs, partiql-value/src/tuple.rs, partiql/tests/user_context.rs
- update nightly toolchain used in CI testing 
- update deny/about for downstream license updates
- backport of https://github.com/partiql/partiql-lang-rust/pull/518 (see below)
- lots of clippy changes, as clippy/rust 1.83 changes some lifetime things to errors
---
Fix the following as reported by `cargo deny check`
```
error[unmaintained]: `derivative` is unmaintained; consider using an alternative
┌─ /Users/joshps/work/partiql-lang-rust/Cargo.lock:55:1
│
55 │ derivative 2.2.0 registry+https://github.com/rust-lang/crates.io-index
│ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ unmaintained advisory detected
│
├ ID: RUSTSEC-2024-0388
├ Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0388
├ The [`derivative`](https://crates.io/crates/derivative) crate is no …
```
=> Fix build & advisory issues.

partiql-eval/src/eval/expr/coll.rs, partiql-eval/src/eval/expr/datetime.rs, partiql-eval/src/eval/expr/functions.rs, partiql-eval/src/eval/expr/mod.rs, partiql-eval/src/eval/expr/operators.rs, partiql-eval/src/eval/expr/path.rs, partiql-eval/src/eval/expr/pattern_match.rs, partiql-eval/src/eval/expr/strings.rs, partiql-eval/src/plan.rs
Optimization: Make `bind` consume.
The values were never re-used anywhere anyway, and this reduces `clone`s.
---
=> Make `bind` consuming

extension/partiql-extension-visualize/src/ast_to_dot.rs, partiql-ast/src/ast.rs, partiql-ast/src/pretty.rs, partiql-logical-planner/src/lower.rs, partiql-parser/src/parse/partiql.lalrpop
=> Add type to `ast::Lit::EmbeddedDocLit`

.github/workflows/ci_build_test.yml
*Issue #, if available:* None
Conformance comparison report was pulling from the source branch rather than the target branch. Uses the prior action, https://github.com/dawidd6/action-download-artifact, with an updated version, which supports pulling specific commit artifacts.
=> Fix conformance comparison report base branch

extension/partiql-extension-ion/src/decode.rs, partiql-conformance-test-generator/Cargo.toml, partiql-conformance-test-generator/src/util.rs
The test name in the input source are sometimes camelCase, somtimes snake_case, sometimes include ALLCAPS, and sometimes just space separated. This attempts to handle all these cases, as well as them being mixed, when generating output test function names.
The best place to see an example of the changes is in the new tests:
https://github.com/partiql/partiql-lang-rust/pull/531/files#diff-32bd33373ab1201cb93b5adcb18518713148844aef6b0807f26a221b792d031cR110-R121
Cf #511 
I do expect the conformance test report for this PR to potentially show changes due to this renaming, though I'm not sure it actually tracks tests that are removed or added, which is what this will appear as.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> Fix conformance test name generation for mixed camel-/snake-case

extension/partiql-extension-ddl/src/ddl.rs, extension/partiql-extension-ddl/tests/ddl-tests.rs, partiql-ast/src/builder.rs, partiql-common/src/node.rs, partiql-eval/src/eval/eval_expr_wrapper.rs, partiql-eval/src/eval/expr/coll.rs, partiql-eval/src/eval/expr/datetime.rs, partiql-eval/src/eval/expr/functions.rs, partiql-eval/src/eval/expr/operators.rs, partiql-eval/src/eval/expr/pattern_match.rs, partiql-eval/src/eval/expr/strings.rs, partiql-logical-planner/src/lower.rs, partiql-logical-planner/src/typer.rs, partiql-types/src/lib.rs
I had issues practically using Shapes with Ids in an external project. I began fixing one thing, and ended up with this refactor.
Esentially, this removes usages of `Arc`s and allows control of the `ID` generation by using a builder that is threaded through type creation. While this is slightly less ergonomic, it allows serialization/deserialization, test cases, etc.
In addition to these changes, I also think that we will need to add `ID`s to, for example, undefined and dynamic types, not just static in the future.
---
=> Feat refactor shape builder

extension/partiql-extension-ion-functions/src/lib.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/coll.rs, partiql-eval/src/eval/expr/mod.rs, partiql-eval/src/eval/expr/operators.rs, partiql-eval/src/eval/expr/path.rs, partiql-eval/src/plan.rs, partiql-value/src/datum.rs, partiql-value/src/lib.rs, partiql-value/src/value.rs, partiql/tests/user_context.rs
This PR introduces `Datum` and `DatumCategory`. These serve as interfaces for abstracting certain properties of PartiQL `Value`s without introspecting the `Value` directly.
This forms part of the basis for supporting external `Variant`s. 
Cf. https://github.com/partiql/partiql-lang-rust/pull/529
---
=> Introduce Datum, an interface to introspecting Values

partiql-logical/src/lib.rs, partiql-value/src/bindings.rs, partiql-value/src/tuple.rs
This PR refactors maching of `BindingsName`s into a `BindingsMatcher`
---
=> Refactor matching of `BindingsName`

partiql-eval/src/eval/eval_expr_wrapper.rs, partiql-types/src/lib.rs, partiql-value/src/datum.rs
This PR introduces `StaticCategory`, a parallel to `DatumCategory`. This aides in type-checking against `Datum`/`DatumCategory`.
This forms part of the basis for supporting external `Variant`s. 
Cf. https://github.com/partiql/partiql-lang-rust/pull/529
---
=> Add `category` for `PartiqlShape`

partiql-conformance-tests/tests/mod.rs, partiql-conformance-tests/tests/test_value.rs, partiql-eval/src/eval/expr/operators.rs, partiql-value/src/bag.rs, partiql-value/src/comparison.rs, partiql-value/src/lib.rs, partiql-value/src/list.rs, partiql-value/src/sort.rs, partiql-value/src/tuple.rs, partiql-value/src/value.rs
This change refactors equality to more closely (and more visibly) reflect the specification's description in [7.1.1](https://partiql.org/assets/PartiQL-Specification.pdf#subsubsection.7.1.1)
This change also adds the ability to perform comparisons where `NULL == NULL` and/or `NaN == NaN` for the purposes of asserting test results more easily.
--
=> Refactor equality as per spec. `eqg` and add testing equality ops

extension/partiql-extension-ion/Cargo.toml, extension/partiql-extension-ion/src/boxed_ion.rs, partiql-value/src/boxed_variant.rs, partiql-value/src/comparison.rs, partiql-value/src/variant.rs
This PR builds on #540 & #542 and adds the ability for comparisons to treat NULLs as equal and/or NaNs as equal.
NaN-equality is mostly of interest for testing against expected examplars.
NULL-equality is used likewise, but also important for compliance with PartiQL's specified semantics for `eqg`.
There are still `todo`s and some additional test failures that will be addressed by future PRs that add functionality.
To see the ultimate end-point of this integration, refer to  #536 and note the test coverage and conformance test results.
---
=> Update ion tests and add null & nan comparisions

.github/workflows/ci_build_test.yml, partiql-ast/src/ast.rs, partiql-eval/src/eval/expr/graph_match.rs, partiql-eval/src/eval/graph/evaluator.rs, partiql-eval/src/eval/graph/mod.rs, partiql-eval/src/eval/graph/plan.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/graph.rs, partiql-logical-planner/src/lib.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/graph/bind_name.rs, partiql-logical/src/graph/mod.rs, partiql-logical/src/lib.rs
This PR:
- Builds on #548 and #549
- enables the `experimental` conformance tests which include the GPML tests
- Refactors some types and traits into non-`pub` modules.
- Fixes some minor graph evaluation edge case bugs
- Adds lowering from the AST to the logical plan for graph match stuff.
---
Some of the graph conformance tests are still failing; These are largely tests that specify only an edge and have implicit start and end nodes (e.g., `( graph MATCH -> )`).
The current grammar cannot parse such a construction. I intend to tackle this in follow-up work, perhaps including modernizing the grammar to follow SQL '23.
---
=> Add lowering from AST to logical plan for graph MATCH

.github/workflows/ci_build_test.yml, partiql-ast/src/ast.rs, partiql-catalog/src/scalar_fn.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/graph_match.rs, partiql-eval/src/eval/graph/evaluator.rs, partiql-eval/src/eval/graph/mod.rs, partiql-eval/src/eval/graph/plan.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/builtins.rs, partiql-logical-planner/src/graph.rs, partiql-logical-planner/src/lib.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/graph/bind_name.rs, partiql-logical/src/graph/mod.rs, partiql-logical/src/lib.rs
Note: this is a recapitulation of #551, as that got merged to the wrong branch
---
This PR:
- Builds on #548 and #549
- enables the `experimental` conformance tests which include the GPML tests
- Refactors some types and traits into non-`pub` modules.
- Fixes some minor graph evaluation edge case bugs
- Adds lowering from the AST to the logical plan for graph match stuff.
---
Some of the graph conformance tests are still failing; These are largely tests that specify only an edge and have implicit start and end nodes (e.g., `( graph MATCH -> )`).
The current grammar cannot parse such a construction. I intend to tackle this in follow-up work, perhaps including modernizing the grammar to follow SQL '23.
---
By submitting this pull request, I confirm that my contribution is made under the …
=> Add lowering from AST to logical plan for graph MATCH 

extension/partiql-extension-visualize/src/plan_to_dot.rs, partiql-eval/benches/bench_eval.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/lib.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql-value/src/value.rs, partiql/tests/queries.rs, partiql/tests/snapshots/queries__select_star_unpivot.snap
Make project-all work with the modeling of `UNPIVOT`
---
=> Feat project all

CHANGELOG.md, extension/partiql-extension-visualize/src/ast_to_dot.rs, partiql-ast/src/ast/mod.rs, partiql-ast/src/pretty/mod.rs, partiql-ast/src/visit.rs, partiql-logical-planner/src/lower.rs
Minor cleanup to remove no-longer used s-expression AST nodes
---
=> Remove SExp from AST

partiql-ast/src/ast/mod.rs, partiql-common/src/node.rs, partiql-conformance-tests/tests/mod.rs, partiql-logical-planner/src/lower.rs
This PR:
- stores the AST node id of the source of the expression along with the transformed expression during lowering
- adds a helper to remove an expression from the set of expressions by the id of the source
---
=> Add AST source NodeId to lower's expression stack

partiql-ast-passes/src/name_resolver.rs, partiql-eval/src/eval/eval_expr_wrapper.rs, partiql-eval/src/eval/evaluable.rs, partiql-eval/src/eval/expr/graph_match.rs, partiql-eval/src/eval/graph/engine.rs, partiql-eval/src/eval/graph/evaluator.rs, partiql-eval/src/eval/graph/plan.rs, partiql-eval/src/eval/graph/simple_graph/engine.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/graph.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/graph/mod.rs, partiql-value/src/datum.rs, partiql-value/src/value.rs
Lower & evaluate `WHERE` filters on node and edge pattern matches in a `GRAPH MATCH` expression.
This involves plumbing some context and bind-name information through to the graph evaluator that was not previously necessary.
See new tests that are expected to pass: 
https://github.com/partiql/partiql-tests/pull/136
---
=> Add value filtering of nodes and edges

CHANGELOG.md, partiql-eval/src/eval/expr/graph_match.rs, partiql-eval/src/eval/graph/engine.rs, partiql-eval/src/eval/graph/evaluator.rs, partiql-eval/src/eval/graph/plan.rs, partiql-eval/src/eval/graph/result.rs, partiql-eval/src/eval/graph/simple_graph/engine.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/graph.rs, partiql-logical/src/graph/bind_name.rs, partiql-logical/src/graph/mod.rs, partiql-value/src/bindings.rs, partiql-value/src/datum.rs, partiql-value/src/value.rs
Lower & evaluate `WHERE` filters on paths and subpaths in `GRAPH MATCH` expression.
This involves plumbing some context and bind-name information through to the graph evaluator that was not previously necessary.
See new tests that are expected to pass: 
https://github.com/partiql/partiql-tests/pull/137
https://github.com/partiql/partiql-tests/pull/138
---
=> Add value filtering of paths and subpaths

partiql-ast/src/ast/mod.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/lower.rs, partiql-logical/src/lib.rs, partiql-parser/src/parse/partiql.lalrpop, partiql-value/src/value.rs
There are some new lints that came along with rust 1.87.
This PR addresses those.
For example:
```
warning: large size difference between variants
--> partiql-ast/src/ast/mod.rs:398:1
|
398 | / pub enum Expr {
399 | |     Lit(AstNode<Lit>),
| |     ----------------- the second-largest variant contains at least 64 bytes
400 | |     /// Variable reference
401 | |     VarRef(AstNode<VarRef>),
...   |
420 | |     GraphMatch(AstNode<GraphMatch>),
| |     ------------------------------- the largest variant contains at least 272 bytes
...   |
427 | |     Error,
428 | | }
| |_^ the entire enum is at least 272 bytes
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#large_enum_variant
note: the lint level is defined here
--> partiql-ast/src/lib.rs:2:9 …
```
=> Clean-up some clippy and rust warnings

CHANGELOG.md, partiql-ast/src/ast/graph.rs, partiql-ast/src/pretty/graph.rs, partiql-eval/src/eval/expr/graph_match.rs, partiql-eval/src/eval/graph/engine.rs, partiql-eval/src/eval/graph/evaluator.rs, partiql-eval/src/eval/graph/plan.rs, partiql-eval/src/eval/graph/simple_graph/engine.rs, partiql-eval/src/plan.rs, partiql-logical-planner/src/graph.rs, partiql-logical/src/graph/mod.rs, partiql-parser/src/parse/partiql.lalrpop
Lower & evaluate Graph Match Modes (`WALK`, `TRAIL`, `ACYCLIC`, `SIMPLE`) on paths and subpaths in `GRAPH MATCH` expression.
See new tests that are expected to pass: 
https://github.com/partiql/partiql-tests/pull/139
---
=> Lower & evaluate Graph Match Modes
